sudo: required

matrix:
  include:
    - name: "Python Tests"
      language: python
      python: 3.6
      install:
        - pip install codecov
        - pip install flake8
        - pip install mypy
        - pip install pylint
        - pip install pyparsing
      script:
        - make test_python
      after_success:
        - codecov

    - name: "SPARK Tests"
      env: TARGET="test_spark"

    - name: "SPARK Tests (without prefix)"
      env: TARGET="test_spark NOPREFIX=1"

    - name: "SPARK Verification"
      env: TARGET="prove_spark_ci"

script:
  - docker run -v $PWD:/app -w /app jklmnn/gnat:gpl.2019.spark /bin/sh -c "make ${TARGET}"
