sudo: required

jobs:
  include:
    - name: "Python Tests"
      language: python
      python:
        - 3.6
      install:
        - pip install codecov
        - pip install flake8
        - pip install mypy
        - pip install pylint
        - pip install pyparsing
      script:
        - make test_python
      after_success:
        - codecov

    - name: "SPARK Tests"
      language: c
      services:
        - docker
      script:
        - docker run -v $PWD:/app -w /app jklmnn/gnat:gpl.2019.spark /bin/sh -c "make test_spark && make prove_spark"
