[workspace]
members = ["librapidflux", "rapidflux"]
resolver = "2"

[workspace.dependencies]
annotate-snippets = "0.11.4"
anstream = "0.6.14"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
lazy_static = "1.4.0"
