import pytest
from pygments import token

import tools.rflxlexer
from rflx.rapidflux import RecordFluxError
from tests.const import FEATURE_DIR

# ruff: noqa: SLF001


def test_calculate_offset_valid() -> None:
    assert tools.rflxlexer._calculate_offset("a", 1, 1) == 0
    assert tools.rflxlexer._calculate_offset("abc", 1, 2) == 1
    assert tools.rflxlexer._calculate_offset("abc\ndef", 2, 2) == 5
    assert tools.rflxlexer._calculate_offset("abc\n\ndef", 3, 2) == 6


def test_calculate_offset_invalid() -> None:
    with pytest.raises(RecordFluxError, match="^<stdin>:2:1: error: line out of range$"):
        tools.rflxlexer._calculate_offset("", 2, 1)

    with pytest.raises(RecordFluxError, match="^<stdin>:2:4: error: column out of range$"):
        tools.rflxlexer._calculate_offset("1234232\n1", 2, 4)


def test_message_tokenization() -> None:
    lexer = tools.rflxlexer.RFLXLexer()
    with (FEATURE_DIR / "shared" / "universal.rflx").open(encoding="utf-8") as f:
        tokens = list(lexer.get_tokens_unprocessed(f.read()))

    assert tokens == [
        (0, token.Keyword, "package"),
        (7, token.Text.Whitespace, " "),
        (8, token.Text, "Universal"),
        (17, token.Text.Whitespace, " "),
        (18, token.Keyword, "is"),
        (20, token.Text, "\n\n"),
        (22, token.Text.Whitespace, "   "),
        (25, token.Keyword, "type"),
        (29, token.Text.Whitespace, " "),
        (30, token.Text, "Message_Type"),
        (42, token.Text.Whitespace, " "),
        (43, token.Keyword, "is"),
        (45, token.Text.Whitespace, " "),
        (46, token.Punctuation, "("),
        (47, token.Text, "MT_Null"),
        (54, token.Text.Whitespace, " "),
        (55, token.Operator, "=>"),
        (57, token.Text.Whitespace, " "),
        (58, token.Literal.Number, "0"),
        (59, token.Punctuation, ","),
        (60, token.Text, "\n"),
        (61, token.Text.Whitespace, "                         "),
        (86, token.Text, "MT_Data"),
        (93, token.Text.Whitespace, " "),
        (94, token.Operator, "=>"),
        (96, token.Text.Whitespace, " "),
        (97, token.Literal.Number, "1"),
        (98, token.Punctuation, ","),
        (99, token.Text, "\n"),
        (100, token.Text.Whitespace, "                         "),
        (125, token.Text, "MT_Value"),
        (133, token.Text.Whitespace, " "),
        (134, token.Operator, "=>"),
        (136, token.Text.Whitespace, " "),
        (137, token.Literal.Number, "2"),
        (138, token.Punctuation, ","),
        (139, token.Text, "\n"),
        (140, token.Text.Whitespace, "                         "),
        (165, token.Text, "MT_Values"),
        (174, token.Text.Whitespace, " "),
        (175, token.Operator, "=>"),
        (177, token.Text.Whitespace, " "),
        (178, token.Literal.Number, "3"),
        (179, token.Punctuation, ","),
        (180, token.Text, "\n"),
        (181, token.Text.Whitespace, "                         "),
        (206, token.Text, "MT_Option_Types"),
        (221, token.Text.Whitespace, " "),
        (222, token.Operator, "=>"),
        (224, token.Text.Whitespace, " "),
        (225, token.Literal.Number, "4"),
        (226, token.Punctuation, ","),
        (227, token.Text, "\n"),
        (228, token.Text.Whitespace, "                         "),
        (253, token.Text, "MT_Options"),
        (263, token.Text.Whitespace, " "),
        (264, token.Operator, "=>"),
        (266, token.Text.Whitespace, " "),
        (267, token.Literal.Number, "5"),
        (268, token.Punctuation, ","),
        (269, token.Text, "\n"),
        (270, token.Text.Whitespace, "                         "),
        (295, token.Text, "MT_Unconstrained_Data"),
        (316, token.Text.Whitespace, " "),
        (317, token.Operator, "=>"),
        (319, token.Text.Whitespace, " "),
        (320, token.Literal.Number, "6"),
        (321, token.Punctuation, ","),
        (322, token.Text, "\n"),
        (323, token.Text.Whitespace, "                         "),
        (348, token.Text, "MT_Unconstrained_Options"),
        (372, token.Text.Whitespace, " "),
        (373, token.Operator, "=>"),
        (375, token.Text.Whitespace, " "),
        (376, token.Literal.Number, "7"),
        (377, token.Punctuation, ")"),
        (378, token.Text.Whitespace, " "),
        (379, token.Keyword, "with"),
        (383, token.Text.Whitespace, " "),
        (384, token.Text, "Size"),
        (388, token.Text.Whitespace, " "),
        (389, token.Operator, "=>"),
        (391, token.Text.Whitespace, " "),
        (392, token.Literal.Number, "8"),
        (393, token.Punctuation, ";"),
        (394, token.Text, "\n\n"),
        (396, token.Text.Whitespace, "   "),
        (399, token.Keyword, "type"),
        (403, token.Text.Whitespace, " "),
        (404, token.Text, "Length"),
        (410, token.Text.Whitespace, " "),
        (411, token.Keyword, "is"),
        (413, token.Text.Whitespace, " "),
        (414, token.Keyword, "range"),
        (419, token.Text.Whitespace, " "),
        (420, token.Literal.Number, "0"),
        (421, token.Text.Whitespace, " "),
        (422, token.Operator, ".."),
        (424, token.Text.Whitespace, " "),
        (425, token.Literal.Number, "2"),
        (426, token.Text.Whitespace, " "),
        (427, token.Operator, "**"),
        (429, token.Text.Whitespace, " "),
        (430, token.Literal.Number, "16"),
        (432, token.Text.Whitespace, " "),
        (433, token.Operator, "-"),
        (434, token.Text.Whitespace, " "),
        (435, token.Literal.Number, "1"),
        (436, token.Text.Whitespace, " "),
        (437, token.Keyword, "with"),
        (441, token.Text.Whitespace, " "),
        (442, token.Text, "Size"),
        (446, token.Text.Whitespace, " "),
        (447, token.Operator, "=>"),
        (449, token.Text.Whitespace, " "),
        (450, token.Literal.Number, "16"),
        (452, token.Punctuation, ";"),
        (453, token.Text, "\n\n"),
        (455, token.Text.Whitespace, "   "),
        (458, token.Keyword, "type"),
        (462, token.Text.Whitespace, " "),
        (463, token.Text, "Value"),
        (468, token.Text.Whitespace, " "),
        (469, token.Keyword, "is"),
        (471, token.Text.Whitespace, " "),
        (472, token.Keyword, "range"),
        (477, token.Text.Whitespace, " "),
        (478, token.Literal.Number, "0"),
        (479, token.Text.Whitespace, " "),
        (480, token.Operator, ".."),
        (482, token.Text.Whitespace, " "),
        (483, token.Literal.Number, "255"),
        (486, token.Text.Whitespace, " "),
        (487, token.Keyword, "with"),
        (491, token.Text.Whitespace, " "),
        (492, token.Text, "Size"),
        (496, token.Text.Whitespace, " "),
        (497, token.Operator, "=>"),
        (499, token.Text.Whitespace, " "),
        (500, token.Literal.Number, "8"),
        (501, token.Punctuation, ";"),
        (502, token.Text, "\n\n"),
        (504, token.Text.Whitespace, "   "),
        (507, token.Keyword, "type"),
        (511, token.Text.Whitespace, " "),
        (512, token.Text, "Values"),
        (518, token.Text.Whitespace, " "),
        (519, token.Keyword, "is"),
        (521, token.Text.Whitespace, " "),
        (522, token.Keyword, "sequence"),
        (530, token.Text.Whitespace, " "),
        (531, token.Keyword, "of"),
        (533, token.Text.Whitespace, " "),
        (534, token.Text, "Value"),
        (539, token.Punctuation, ";"),
        (540, token.Text, "\n\n"),
        (542, token.Text.Whitespace, "   "),
        (545, token.Keyword, "type"),
        (549, token.Text.Whitespace, " "),
        (550, token.Text, "Option_Type"),
        (561, token.Text.Whitespace, " "),
        (562, token.Keyword, "is"),
        (564, token.Text.Whitespace, " "),
        (565, token.Punctuation, "("),
        (566, token.Text, "OT_Null"),
        (573, token.Text.Whitespace, " "),
        (574, token.Operator, "=>"),
        (576, token.Text.Whitespace, " "),
        (577, token.Literal.Number, "0"),
        (578, token.Punctuation, ","),
        (579, token.Text.Whitespace, " "),
        (580, token.Text, "OT_Data"),
        (587, token.Text.Whitespace, " "),
        (588, token.Operator, "=>"),
        (590, token.Text.Whitespace, " "),
        (591, token.Literal.Number, "1"),
        (592, token.Punctuation, ")"),
        (593, token.Text.Whitespace, " "),
        (594, token.Keyword, "with"),
        (598, token.Text.Whitespace, " "),
        (599, token.Text, "Size"),
        (603, token.Text.Whitespace, " "),
        (604, token.Operator, "=>"),
        (606, token.Text.Whitespace, " "),
        (607, token.Literal.Number, "8"),
        (608, token.Punctuation, ","),
        (609, token.Text.Whitespace, " "),
        (610, token.Text, "Always_Valid"),
        (622, token.Text.Whitespace, " "),
        (623, token.Operator, "=>"),
        (625, token.Text.Whitespace, " "),
        (626, token.Text, "True"),
        (630, token.Punctuation, ";"),
        (631, token.Text, "\n\n"),
        (633, token.Text.Whitespace, "   "),
        (636, token.Keyword, "type"),
        (640, token.Text.Whitespace, " "),
        (641, token.Text, "Option_Types"),
        (653, token.Text.Whitespace, " "),
        (654, token.Keyword, "is"),
        (656, token.Text.Whitespace, " "),
        (657, token.Keyword, "sequence"),
        (665, token.Text.Whitespace, " "),
        (666, token.Keyword, "of"),
        (668, token.Text.Whitespace, " "),
        (669, token.Text, "Option_Type"),
        (680, token.Punctuation, ";"),
        (681, token.Text, "\n\n"),
        (683, token.Text.Whitespace, "   "),
        (686, token.Keyword, "type"),
        (690, token.Text.Whitespace, " "),
        (691, token.Text, "Option"),
        (697, token.Text.Whitespace, " "),
        (698, token.Keyword, "is"),
        (700, token.Text, "\n"),
        (701, token.Text.Whitespace, "      "),
        (707, token.Keyword, "message"),
        (714, token.Text, "\n"),
        (715, token.Text.Whitespace, "         "),
        (724, token.Text, "Option_Type"),
        (735, token.Text.Whitespace, " "),
        (736, token.Punctuation, ":"),
        (737, token.Text.Whitespace, " "),
        (738, token.Text, "Option_Type"),
        (749, token.Text, "\n"),
        (750, token.Text.Whitespace, "            "),
        (762, token.Keyword, "then"),
        (766, token.Text.Whitespace, " "),
        (767, token.Keyword, "null"),
        (771, token.Text, "\n"),
        (772, token.Text.Whitespace, "               "),
        (787, token.Keyword, "if"),
        (789, token.Text.Whitespace, " "),
        (790, token.Text, "Option_Type"),
        (801, token.Text.Whitespace, " "),
        (802, token.Operator, "="),
        (803, token.Text.Whitespace, " "),
        (804, token.Text, "OT_Null"),
        (811, token.Text, "\n"),
        (812, token.Text.Whitespace, "            "),
        (824, token.Keyword, "then"),
        (828, token.Text.Whitespace, " "),
        (829, token.Text, "Length"),
        (835, token.Text, "\n"),
        (836, token.Text.Whitespace, "               "),
        (851, token.Keyword, "if"),
        (853, token.Text.Whitespace, " "),
        (854, token.Text, "Option_Type"),
        (865, token.Text.Whitespace, " "),
        (866, token.Operator, "="),
        (867, token.Text.Whitespace, " "),
        (868, token.Text, "OT_Data"),
        (875, token.Punctuation, ";"),
        (876, token.Text, "\n"),
        (877, token.Text.Whitespace, "         "),
        (886, token.Text, "Length"),
        (892, token.Text.Whitespace, " "),
        (893, token.Punctuation, ":"),
        (894, token.Text.Whitespace, " "),
        (895, token.Text, "Length"),
        (901, token.Text, "\n"),
        (902, token.Text.Whitespace, "            "),
        (914, token.Keyword, "then"),
        (918, token.Text.Whitespace, " "),
        (919, token.Text, "Data"),
        (923, token.Text, "\n"),
        (924, token.Text.Whitespace, "               "),
        (939, token.Keyword, "with"),
        (943, token.Text.Whitespace, " "),
        (944, token.Text, "Size"),
        (948, token.Text.Whitespace, " "),
        (949, token.Operator, "=>"),
        (951, token.Text.Whitespace, " "),
        (952, token.Text, "Length"),
        (958, token.Text.Whitespace, " "),
        (959, token.Operator, "*"),
        (960, token.Text.Whitespace, " "),
        (961, token.Literal.Number, "8"),
        (962, token.Punctuation, ";"),
        (963, token.Text, "\n"),
        (964, token.Text.Whitespace, "         "),
        (973, token.Text, "Data"),
        (977, token.Text.Whitespace, " "),
        (978, token.Punctuation, ":"),
        (979, token.Text.Whitespace, " "),
        (980, token.Text, "Opaque"),
        (986, token.Punctuation, ";"),
        (987, token.Text, "\n"),
        (988, token.Text.Whitespace, "      "),
        (994, token.Keyword, "end"),
        (997, token.Text.Whitespace, " "),
        (998, token.Keyword, "message"),
        (1005, token.Punctuation, ";"),
        (1006, token.Text, "\n\n"),
        (1008, token.Text.Whitespace, "   "),
        (1011, token.Keyword, "type"),
        (1015, token.Text.Whitespace, " "),
        (1016, token.Text, "Options"),
        (1023, token.Text.Whitespace, " "),
        (1024, token.Keyword, "is"),
        (1026, token.Text.Whitespace, " "),
        (1027, token.Keyword, "sequence"),
        (1035, token.Text.Whitespace, " "),
        (1036, token.Keyword, "of"),
        (1038, token.Text.Whitespace, " "),
        (1039, token.Text, "Option"),
        (1045, token.Punctuation, ";"),
        (1046, token.Text, "\n\n"),
        (1048, token.Text.Whitespace, "   "),
        (1051, token.Keyword, "type"),
        (1055, token.Text.Whitespace, " "),
        (1056, token.Text, "Message"),
        (1063, token.Text.Whitespace, " "),
        (1064, token.Keyword, "is"),
        (1066, token.Text, "\n"),
        (1067, token.Text.Whitespace, "      "),
        (1073, token.Keyword, "message"),
        (1080, token.Text, "\n"),
        (1081, token.Text.Whitespace, "         "),
        (1090, token.Text, "Message_Type"),
        (1102, token.Text.Whitespace, " "),
        (1103, token.Punctuation, ":"),
        (1104, token.Text.Whitespace, " "),
        (1105, token.Text, "Message_Type"),
        (1117, token.Text, "\n"),
        (1118, token.Text.Whitespace, "            "),
        (1130, token.Keyword, "then"),
        (1134, token.Text.Whitespace, " "),
        (1135, token.Keyword, "null"),
        (1139, token.Text, "\n"),
        (1140, token.Text.Whitespace, "               "),
        (1155, token.Keyword, "if"),
        (1157, token.Text.Whitespace, " "),
        (1158, token.Text, "Message_Type"),
        (1170, token.Text.Whitespace, " "),
        (1171, token.Operator, "="),
        (1172, token.Text.Whitespace, " "),
        (1173, token.Text, "MT_Null"),
        (1180, token.Text, "\n"),
        (1181, token.Text.Whitespace, "            "),
        (1193, token.Keyword, "then"),
        (1197, token.Text.Whitespace, " "),
        (1198, token.Text, "Data"),
        (1202, token.Text, "\n"),
        (1203, token.Text.Whitespace, "               "),
        (1218, token.Keyword, "with"),
        (1222, token.Text.Whitespace, " "),
        (1223, token.Text, "Size"),
        (1227, token.Text.Whitespace, " "),
        (1228, token.Operator, "=>"),
        (1230, token.Text.Whitespace, " "),
        (1231, token.Text, "Message"),
        (1238, token.Punctuation, "'"),
        (1239, token.Keyword, "Last"),
        (1243, token.Text.Whitespace, " "),
        (1244, token.Operator, "-"),
        (1245, token.Text.Whitespace, " "),
        (1246, token.Text, "Message_Type"),
        (1258, token.Punctuation, "'"),
        (1259, token.Keyword, "Last"),
        (1263, token.Text, "\n"),
        (1264, token.Text.Whitespace, "               "),
        (1279, token.Keyword, "if"),
        (1281, token.Text.Whitespace, " "),
        (1282, token.Text, "Message_Type"),
        (1294, token.Text.Whitespace, " "),
        (1295, token.Operator, "="),
        (1296, token.Text.Whitespace, " "),
        (1297, token.Text, "MT_Unconstrained_Data"),
        (1318, token.Text, "\n"),
        (1319, token.Text.Whitespace, "            "),
        (1331, token.Keyword, "then"),
        (1335, token.Text.Whitespace, " "),
        (1336, token.Text, "Length"),
        (1342, token.Text, "\n"),
        (1343, token.Text.Whitespace, "               "),
        (1358, token.Keyword, "if"),
        (1360, token.Text.Whitespace, " "),
        (1361, token.Text, "Message_Type"),
        (1373, token.Text.Whitespace, " "),
        (1374, token.Operator, "/="),
        (1376, token.Text.Whitespace, " "),
        (1377, token.Text, "MT_Null"),
        (1384, token.Text, "\n"),
        (1385, token.Text.Whitespace, "                  "),
        (1403, token.Operator.Text, "and"),
        (1406, token.Text.Whitespace, " "),
        (1407, token.Text, "Message_Type"),
        (1419, token.Text.Whitespace, " "),
        (1420, token.Operator, "/="),
        (1422, token.Text.Whitespace, " "),
        (1423, token.Text, "MT_Unconstrained_Data"),
        (1444, token.Text, "\n"),
        (1445, token.Text.Whitespace, "                  "),
        (1463, token.Operator.Text, "and"),
        (1466, token.Text.Whitespace, " "),
        (1467, token.Text, "Message_Type"),
        (1479, token.Text.Whitespace, " "),
        (1480, token.Operator, "/="),
        (1482, token.Text.Whitespace, " "),
        (1483, token.Text, "MT_Unconstrained_Options"),
        (1507, token.Text, "\n"),
        (1508, token.Text.Whitespace, "            "),
        (1520, token.Keyword, "then"),
        (1524, token.Text.Whitespace, " "),
        (1525, token.Text, "Options"),
        (1532, token.Text, "\n"),
        (1533, token.Text.Whitespace, "               "),
        (1548, token.Keyword, "with"),
        (1552, token.Text.Whitespace, " "),
        (1553, token.Text, "Size"),
        (1557, token.Text.Whitespace, " "),
        (1558, token.Operator, "=>"),
        (1560, token.Text.Whitespace, " "),
        (1561, token.Text, "Message"),
        (1568, token.Punctuation, "'"),
        (1569, token.Keyword, "Last"),
        (1573, token.Text.Whitespace, " "),
        (1574, token.Operator, "-"),
        (1575, token.Text.Whitespace, " "),
        (1576, token.Text, "Message_Type"),
        (1588, token.Punctuation, "'"),
        (1589, token.Keyword, "Last"),
        (1593, token.Text, "\n"),
        (1594, token.Text.Whitespace, "               "),
        (1609, token.Keyword, "if"),
        (1611, token.Text.Whitespace, " "),
        (1612, token.Text, "Message_Type"),
        (1624, token.Text.Whitespace, " "),
        (1625, token.Operator, "="),
        (1626, token.Text.Whitespace, " "),
        (1627, token.Text, "MT_Unconstrained_Options"),
        (1651, token.Punctuation, ";"),
        (1652, token.Text, "\n"),
        (1653, token.Text.Whitespace, "         "),
        (1662, token.Text, "Length"),
        (1668, token.Text.Whitespace, " "),
        (1669, token.Punctuation, ":"),
        (1670, token.Text.Whitespace, " "),
        (1671, token.Text, "Length"),
        (1677, token.Text, "\n"),
        (1678, token.Text.Whitespace, "            "),
        (1690, token.Keyword, "then"),
        (1694, token.Text.Whitespace, " "),
        (1695, token.Text, "Data"),
        (1699, token.Text, "\n"),
        (1700, token.Text.Whitespace, "               "),
        (1715, token.Keyword, "with"),
        (1719, token.Text.Whitespace, " "),
        (1720, token.Text, "Size"),
        (1724, token.Text.Whitespace, " "),
        (1725, token.Operator, "=>"),
        (1727, token.Text.Whitespace, " "),
        (1728, token.Text, "Length"),
        (1734, token.Text.Whitespace, " "),
        (1735, token.Operator, "*"),
        (1736, token.Text.Whitespace, " "),
        (1737, token.Literal.Number, "8"),
        (1738, token.Text, "\n"),
        (1739, token.Text.Whitespace, "               "),
        (1754, token.Keyword, "if"),
        (1756, token.Text.Whitespace, " "),
        (1757, token.Text, "Message_Type"),
        (1769, token.Text.Whitespace, " "),
        (1770, token.Operator, "="),
        (1771, token.Text.Whitespace, " "),
        (1772, token.Text, "MT_Data"),
        (1779, token.Text, "\n"),
        (1780, token.Text.Whitespace, "            "),
        (1792, token.Keyword, "then"),
        (1796, token.Text.Whitespace, " "),
        (1797, token.Text, "Option_Types"),
        (1809, token.Text, "\n"),
        (1810, token.Text.Whitespace, "               "),
        (1825, token.Keyword, "with"),
        (1829, token.Text.Whitespace, " "),
        (1830, token.Text, "Size"),
        (1834, token.Text.Whitespace, " "),
        (1835, token.Operator, "=>"),
        (1837, token.Text.Whitespace, " "),
        (1838, token.Text, "Length"),
        (1844, token.Text.Whitespace, " "),
        (1845, token.Operator, "*"),
        (1846, token.Text.Whitespace, " "),
        (1847, token.Literal.Number, "8"),
        (1848, token.Text, "\n"),
        (1849, token.Text.Whitespace, "               "),
        (1864, token.Keyword, "if"),
        (1866, token.Text.Whitespace, " "),
        (1867, token.Text, "Message_Type"),
        (1879, token.Text.Whitespace, " "),
        (1880, token.Operator, "="),
        (1881, token.Text.Whitespace, " "),
        (1882, token.Text, "MT_Option_Types"),
        (1897, token.Text, "\n"),
        (1898, token.Text.Whitespace, "            "),
        (1910, token.Keyword, "then"),
        (1914, token.Text.Whitespace, " "),
        (1915, token.Text, "Options"),
        (1922, token.Text, "\n"),
        (1923, token.Text.Whitespace, "               "),
        (1938, token.Keyword, "with"),
        (1942, token.Text.Whitespace, " "),
        (1943, token.Text, "Size"),
        (1947, token.Text.Whitespace, " "),
        (1948, token.Operator, "=>"),
        (1950, token.Text.Whitespace, " "),
        (1951, token.Text, "Length"),
        (1957, token.Text.Whitespace, " "),
        (1958, token.Operator, "*"),
        (1959, token.Text.Whitespace, " "),
        (1960, token.Literal.Number, "8"),
        (1961, token.Text, "\n"),
        (1962, token.Text.Whitespace, "               "),
        (1977, token.Keyword, "if"),
        (1979, token.Text.Whitespace, " "),
        (1980, token.Text, "Message_Type"),
        (1992, token.Text.Whitespace, " "),
        (1993, token.Operator, "="),
        (1994, token.Text.Whitespace, " "),
        (1995, token.Text, "MT_Options"),
        (2005, token.Text, "\n"),
        (2006, token.Text.Whitespace, "            "),
        (2018, token.Keyword, "then"),
        (2022, token.Text.Whitespace, " "),
        (2023, token.Text, "Value"),
        (2028, token.Text, "\n"),
        (2029, token.Text.Whitespace, "               "),
        (2044, token.Keyword, "if"),
        (2046, token.Text.Whitespace, " "),
        (2047, token.Text, "Message_Type"),
        (2059, token.Text.Whitespace, " "),
        (2060, token.Operator, "="),
        (2061, token.Text.Whitespace, " "),
        (2062, token.Text, "MT_Value"),
        (2070, token.Text, "\n"),
        (2071, token.Text.Whitespace, "                  "),
        (2089, token.Operator.Text, "and"),
        (2092, token.Text.Whitespace, " "),
        (2093, token.Text, "Length"),
        (2099, token.Text.Whitespace, " "),
        (2100, token.Operator, "="),
        (2101, token.Text.Whitespace, " "),
        (2102, token.Text, "Universal"),
        (2111, token.Punctuation, "::"),
        (2113, token.Text, "Value"),
        (2118, token.Punctuation, "'"),
        (2119, token.Keyword, "Size"),
        (2123, token.Text.Whitespace, " "),
        (2124, token.Operator, "/"),
        (2125, token.Text.Whitespace, " "),
        (2126, token.Literal.Number, "8"),
        (2127, token.Text, "\n"),
        (2128, token.Text.Whitespace, "            "),
        (2140, token.Keyword, "then"),
        (2144, token.Text.Whitespace, " "),
        (2145, token.Text, "Values"),
        (2151, token.Text, "\n"),
        (2152, token.Text.Whitespace, "               "),
        (2167, token.Keyword, "with"),
        (2171, token.Text.Whitespace, " "),
        (2172, token.Text, "Size"),
        (2176, token.Text.Whitespace, " "),
        (2177, token.Operator, "=>"),
        (2179, token.Text.Whitespace, " "),
        (2180, token.Text, "Length"),
        (2186, token.Text.Whitespace, " "),
        (2187, token.Operator, "*"),
        (2188, token.Text.Whitespace, " "),
        (2189, token.Literal.Number, "8"),
        (2190, token.Text, "\n"),
        (2191, token.Text.Whitespace, "               "),
        (2206, token.Keyword, "if"),
        (2208, token.Text.Whitespace, " "),
        (2209, token.Text, "Message_Type"),
        (2221, token.Text.Whitespace, " "),
        (2222, token.Operator, "="),
        (2223, token.Text.Whitespace, " "),
        (2224, token.Text, "MT_Values"),
        (2233, token.Punctuation, ";"),
        (2234, token.Text, "\n"),
        (2235, token.Text.Whitespace, "         "),
        (2244, token.Text, "Data"),
        (2248, token.Text.Whitespace, " "),
        (2249, token.Punctuation, ":"),
        (2250, token.Text.Whitespace, " "),
        (2251, token.Text, "Opaque"),
        (2257, token.Text, "\n"),
        (2258, token.Text.Whitespace, "            "),
        (2270, token.Keyword, "then"),
        (2274, token.Text.Whitespace, " "),
        (2275, token.Keyword, "null"),
        (2279, token.Punctuation, ";"),
        (2280, token.Text, "\n"),
        (2281, token.Text.Whitespace, "         "),
        (2290, token.Text, "Option_Types"),
        (2302, token.Text.Whitespace, " "),
        (2303, token.Punctuation, ":"),
        (2304, token.Text.Whitespace, " "),
        (2305, token.Text, "Option_Types"),
        (2317, token.Text, "\n"),
        (2318, token.Text.Whitespace, "            "),
        (2330, token.Keyword, "then"),
        (2334, token.Text.Whitespace, " "),
        (2335, token.Keyword, "null"),
        (2339, token.Punctuation, ";"),
        (2340, token.Text, "\n"),
        (2341, token.Text.Whitespace, "         "),
        (2350, token.Text, "Options"),
        (2357, token.Text.Whitespace, " "),
        (2358, token.Punctuation, ":"),
        (2359, token.Text.Whitespace, " "),
        (2360, token.Text, "Options"),
        (2367, token.Text, "\n"),
        (2368, token.Text.Whitespace, "            "),
        (2380, token.Keyword, "then"),
        (2384, token.Text.Whitespace, " "),
        (2385, token.Keyword, "null"),
        (2389, token.Punctuation, ";"),
        (2390, token.Text, "\n"),
        (2391, token.Text.Whitespace, "         "),
        (2400, token.Text, "Value"),
        (2405, token.Text.Whitespace, " "),
        (2406, token.Punctuation, ":"),
        (2407, token.Text.Whitespace, " "),
        (2408, token.Text, "Value"),
        (2413, token.Text, "\n"),
        (2414, token.Text.Whitespace, "            "),
        (2426, token.Keyword, "then"),
        (2430, token.Text.Whitespace, " "),
        (2431, token.Keyword, "null"),
        (2435, token.Punctuation, ";"),
        (2436, token.Text, "\n"),
        (2437, token.Text.Whitespace, "         "),
        (2446, token.Text, "Values"),
        (2452, token.Text.Whitespace, " "),
        (2453, token.Punctuation, ":"),
        (2454, token.Text.Whitespace, " "),
        (2455, token.Text, "Values"),
        (2461, token.Punctuation, ";"),
        (2462, token.Text, "\n"),
        (2463, token.Text.Whitespace, "      "),
        (2469, token.Keyword, "end"),
        (2472, token.Text.Whitespace, " "),
        (2473, token.Keyword, "message"),
        (2480, token.Punctuation, ";"),
        (2481, token.Text, "\n\n"),
        (2483, token.Text.Whitespace, "   "),
        (2486, token.Keyword, "for"),
        (2489, token.Text.Whitespace, " "),
        (2490, token.Text, "Message"),
        (2497, token.Text.Whitespace, " "),
        (2498, token.Keyword, "use"),
        (2501, token.Text.Whitespace, " "),
        (2502, token.Punctuation, "("),
        (2503, token.Text, "Data"),
        (2507, token.Text.Whitespace, " "),
        (2508, token.Operator, "=>"),
        (2510, token.Text.Whitespace, " "),
        (2511, token.Text, "Option"),
        (2517, token.Punctuation, ")"),
        (2518, token.Punctuation, ";"),
        (2519, token.Text, "\n\n"),
        (2521, token.Keyword, "end"),
        (2524, token.Text.Whitespace, " "),
        (2525, token.Text, "Universal"),
        (2534, token.Punctuation, ";"),
        (2535, token.Text, "\n"),
    ]


def test_state_machine_tokenization() -> None:
    lexer = tools.rflxlexer.RFLXLexer()
    with (FEATURE_DIR / "fsm_functions" / "test.rflx").open(encoding="utf-8") as f:
        tokens = list(lexer.get_tokens_unprocessed(f.read()))

    assert tokens == [
        (0, token.Keyword, "with"),
        (4, token.Text.Whitespace, " "),
        (5, token.Text, "Universal"),
        (14, token.Punctuation, ";"),
        (15, token.Text, "\n\n"),
        (17, token.Keyword, "package"),
        (24, token.Text.Whitespace, " "),
        (25, token.Text, "Test"),
        (29, token.Text.Whitespace, " "),
        (30, token.Keyword, "is"),
        (32, token.Text, "\n\n"),
        (34, token.Text.Whitespace, "   "),
        (37, token.Keyword, "type"),
        (41, token.Text.Whitespace, " "),
        (42, token.Text, "Result"),
        (48, token.Text.Whitespace, " "),
        (49, token.Keyword, "is"),
        (51, token.Text.Whitespace, " "),
        (52, token.Punctuation, "("),
        (53, token.Text, "M_Valid"),
        (60, token.Punctuation, ","),
        (61, token.Text.Whitespace, " "),
        (62, token.Text, "M_Invalid"),
        (71, token.Punctuation, ")"),
        (72, token.Text.Whitespace, " "),
        (73, token.Keyword, "with"),
        (77, token.Text.Whitespace, " "),
        (78, token.Text, "Size"),
        (82, token.Text.Whitespace, " "),
        (83, token.Operator, "=>"),
        (85, token.Text.Whitespace, " "),
        (86, token.Literal.Number, "2"),
        (87, token.Punctuation, ";"),
        (88, token.Text, "\n\n"),
        (90, token.Text.Whitespace, "   "),
        (93, token.Keyword, "type"),
        (97, token.Text.Whitespace, " "),
        (98, token.Text, "Length"),
        (104, token.Text.Whitespace, " "),
        (105, token.Keyword, "is"),
        (107, token.Text.Whitespace, " "),
        (108, token.Keyword, "range"),
        (113, token.Text.Whitespace, " "),
        (114, token.Literal.Number, "0"),
        (115, token.Text.Whitespace, " "),
        (116, token.Operator, ".."),
        (118, token.Text.Whitespace, " "),
        (119, token.Literal.Number, "2"),
        (120, token.Text.Whitespace, " "),
        (121, token.Operator, "**"),
        (123, token.Text.Whitespace, " "),
        (124, token.Literal.Number, "8"),
        (125, token.Text.Whitespace, " "),
        (126, token.Operator, "-"),
        (127, token.Text.Whitespace, " "),
        (128, token.Literal.Number, "1"),
        (129, token.Text.Whitespace, " "),
        (130, token.Keyword, "with"),
        (134, token.Text.Whitespace, " "),
        (135, token.Text, "Size"),
        (139, token.Text.Whitespace, " "),
        (140, token.Operator, "=>"),
        (142, token.Text.Whitespace, " "),
        (143, token.Literal.Number, "8"),
        (144, token.Punctuation, ";"),
        (145, token.Text, "\n\n"),
        (147, token.Text.Whitespace, "   "),
        (150, token.Keyword, "type"),
        (154, token.Text.Whitespace, " "),
        (155, token.Text, "Definite_Message"),
        (171, token.Text.Whitespace, " "),
        (172, token.Keyword, "is"),
        (174, token.Text, "\n"),
        (175, token.Text.Whitespace, "      "),
        (181, token.Keyword, "message"),
        (188, token.Text, "\n"),
        (189, token.Text.Whitespace, "         "),
        (198, token.Text, "Message_Type"),
        (210, token.Text.Whitespace, " "),
        (211, token.Punctuation, ":"),
        (212, token.Text.Whitespace, " "),
        (213, token.Text, "Universal"),
        (222, token.Punctuation, "::"),
        (224, token.Text, "Option_Type"),
        (235, token.Punctuation, ";"),
        (236, token.Text, "\n"),
        (237, token.Text.Whitespace, "         "),
        (246, token.Text, "Length"),
        (252, token.Text.Whitespace, " "),
        (253, token.Punctuation, ":"),
        (254, token.Text.Whitespace, " "),
        (255, token.Text, "Length"),
        (261, token.Punctuation, ";"),
        (262, token.Text, "\n"),
        (263, token.Text.Whitespace, "         "),
        (272, token.Text, "Data"),
        (276, token.Text.Whitespace, " "),
        (277, token.Punctuation, ":"),
        (278, token.Text.Whitespace, " "),
        (279, token.Text, "Opaque"),
        (285, token.Text, "\n"),
        (286, token.Text.Whitespace, "            "),
        (298, token.Keyword, "with"),
        (302, token.Text.Whitespace, " "),
        (303, token.Text, "Size"),
        (307, token.Text.Whitespace, " "),
        (308, token.Operator, "=>"),
        (310, token.Text.Whitespace, " "),
        (311, token.Text, "Length"),
        (317, token.Text.Whitespace, " "),
        (318, token.Operator, "*"),
        (319, token.Text.Whitespace, " "),
        (320, token.Literal.Number, "8"),
        (321, token.Punctuation, ";"),
        (322, token.Text, "\n"),
        (323, token.Text.Whitespace, "      "),
        (329, token.Keyword, "end"),
        (332, token.Text.Whitespace, " "),
        (333, token.Keyword, "message"),
        (340, token.Punctuation, ";"),
        (341, token.Text, "\n\n"),
        (343, token.Text.Whitespace, "   "),
        (346, token.Keyword, "generic"),
        (353, token.Text, "\n"),
        (354, token.Text.Whitespace, "      "),
        (360, token.Keyword, "Channel"),
        (367, token.Text.Whitespace, " "),
        (368, token.Punctuation, ":"),
        (369, token.Text.Whitespace, " "),
        (370, token.Keyword, "Channel"),
        (377, token.Text.Whitespace, " "),
        (378, token.Keyword, "with"),
        (382, token.Text.Whitespace, " "),
        (383, token.Keyword, "Readable"),
        (391, token.Punctuation, ","),
        (392, token.Text.Whitespace, " "),
        (393, token.Keyword, "Writable"),
        (401, token.Punctuation, ";"),
        (402, token.Text.Whitespace, " "),
        (403, token.Comment, "-- §S-P-C-RW"),
        (415, token.Text, "\n"),
        (416, token.Text.Whitespace, "      "),
        (422, token.Comment, "-- §S-P-F-R-S"),
        (435, token.Text, "\n"),
        (436, token.Text.Whitespace, "      "),
        (442, token.Keyword, "with"),
        (446, token.Text.Whitespace, " "),
        (447, token.Keyword, "function"),
        (455, token.Text.Whitespace, " "),
        (456, token.Text, "Get_Message_Type"),
        (472, token.Text.Whitespace, " "),
        (473, token.Keyword, "return"),
        (479, token.Text.Whitespace, " "),
        (480, token.Text, "Universal"),
        (489, token.Punctuation, "::"),
        (491, token.Text, "Option_Type"),
        (502, token.Punctuation, ";"),
        (503, token.Text, "\n"),
        (504, token.Text.Whitespace, "      "),
        (510, token.Comment, "-- §S-P-F-P-S, §S-P-F-P-O, §S-P-F-R-M"),
        (547, token.Text, "\n"),
        (548, token.Text.Whitespace, "      "),
        (554, token.Keyword, "with"),
        (558, token.Text.Whitespace, " "),
        (559, token.Keyword, "function"),
        (567, token.Text.Whitespace, " "),
        (568, token.Text, "Create_Message"),
        (582, token.Text, "\n"),
        (583, token.Text.Whitespace, "         "),
        (592, token.Punctuation, "("),
        (593, token.Text, "Message_Type"),
        (605, token.Text.Whitespace, " "),
        (606, token.Punctuation, ":"),
        (607, token.Text.Whitespace, " "),
        (608, token.Text, "Universal"),
        (617, token.Punctuation, "::"),
        (619, token.Text, "Option_Type"),
        (630, token.Punctuation, ";"),
        (631, token.Text, "\n"),
        (632, token.Text.Whitespace, "          "),
        (642, token.Text, "Length"),
        (648, token.Text.Whitespace, " "),
        (649, token.Punctuation, ":"),
        (650, token.Text.Whitespace, " "),
        (651, token.Text, "Length"),
        (657, token.Punctuation, ";"),
        (658, token.Text, "\n"),
        (659, token.Text.Whitespace, "          "),
        (669, token.Text, "Data"),
        (673, token.Text.Whitespace, " "),
        (674, token.Punctuation, ":"),
        (675, token.Text.Whitespace, " "),
        (676, token.Text, "Opaque"),
        (682, token.Punctuation, ")"),
        (683, token.Text, "\n"),
        (684, token.Text.Whitespace, "      "),
        (690, token.Keyword, "return"),
        (696, token.Text.Whitespace, " "),
        (697, token.Text, "Definite_Message"),
        (713, token.Punctuation, ";"),
        (714, token.Text, "\n"),
        (715, token.Text.Whitespace, "      "),
        (721, token.Comment, "-- §S-P-F-P-S, §S-P-F-R-S"),
        (746, token.Text, "\n"),
        (747, token.Text.Whitespace, "      "),
        (753, token.Keyword, "with"),
        (757, token.Text.Whitespace, " "),
        (758, token.Keyword, "function"),
        (766, token.Text.Whitespace, " "),
        (767, token.Text, "Valid_Message"),
        (780, token.Text, "\n"),
        (781, token.Text.Whitespace, "         "),
        (790, token.Punctuation, "("),
        (791, token.Text, "Message_Type"),
        (803, token.Text.Whitespace, " "),
        (804, token.Punctuation, ":"),
        (805, token.Text.Whitespace, " "),
        (806, token.Text, "Universal"),
        (815, token.Punctuation, "::"),
        (817, token.Text, "Option_Type"),
        (828, token.Punctuation, ";"),
        (829, token.Text, "\n"),
        (830, token.Text.Whitespace, "          "),
        (840, token.Text, "Strict"),
        (846, token.Text.Whitespace, " "),
        (847, token.Punctuation, ":"),
        (848, token.Text.Whitespace, " "),
        (849, token.Text, "Boolean"),
        (856, token.Punctuation, ")"),
        (857, token.Text, "\n"),
        (858, token.Text.Whitespace, "      "),
        (864, token.Keyword, "return"),
        (870, token.Text.Whitespace, " "),
        (871, token.Text, "Result"),
        (877, token.Punctuation, ";"),
        (878, token.Text, "\n"),
        (879, token.Text.Whitespace, "      "),
        (885, token.Comment, "-- §S-P-F-R-S"),
        (898, token.Text, "\n"),
        (899, token.Text.Whitespace, "      "),
        (905, token.Keyword, "with"),
        (909, token.Text.Whitespace, " "),
        (910, token.Keyword, "function"),
        (918, token.Text.Whitespace, " "),
        (919, token.Text, "Byte_Size"),
        (928, token.Text.Whitespace, " "),
        (929, token.Keyword, "return"),
        (935, token.Text.Whitespace, " "),
        (936, token.Text, "Length"),
        (942, token.Punctuation, ";"),
        (943, token.Text, "\n"),
        (944, token.Text.Whitespace, "   "),
        (947, token.Keyword, "machine"),
        (954, token.Text.Whitespace, " "),
        (955, token.Text, "S"),
        (956, token.Text.Whitespace, " "),
        (957, token.Keyword, "is"),
        (959, token.Text, "\n"),
        (960, token.Text.Whitespace, "      "),
        (966, token.Text, "Message"),
        (973, token.Text.Whitespace, " "),
        (974, token.Punctuation, ":"),
        (975, token.Text.Whitespace, " "),
        (976, token.Text, "Universal"),
        (985, token.Punctuation, "::"),
        (987, token.Text, "Message"),
        (994, token.Punctuation, ";"),
        (995, token.Text.Whitespace, " "),
        (996, token.Comment, "-- §S-D-V-T-M, §S-D-V-E-N"),
        (1021, token.Text, "\n"),
        (1022, token.Text.Whitespace, "      "),
        (1028, token.Text, "Definite_Message"),
        (1044, token.Text.Whitespace, " "),
        (1045, token.Punctuation, ":"),
        (1046, token.Text.Whitespace, " "),
        (1047, token.Text, "Definite_Message"),
        (1063, token.Punctuation, ";"),
        (1064, token.Text.Whitespace, " "),
        (1065, token.Comment, "-- §S-D-V-T-M, §S-D-V-E-N"),
        (1090, token.Text, "\n"),
        (1091, token.Text.Whitespace, "   "),
        (1094, token.Keyword, "begin"),
        (1099, token.Text, "\n"),
        (1100, token.Text.Whitespace, "      "),
        (1106, token.Keyword, "state"),
        (1111, token.Text.Whitespace, " "),
        (1112, token.Text, "Start"),
        (1117, token.Text.Whitespace, " "),
        (1118, token.Keyword, "is"),
        (1120, token.Text, "\n"),
        (1121, token.Text.Whitespace, "      "),
        (1127, token.Keyword, "begin"),
        (1132, token.Text, "\n"),
        (1133, token.Text.Whitespace, "         "),
        (1142, token.Keyword, "Channel"),
        (1149, token.Punctuation, "'"),
        (1150, token.Keyword, "Read"),
        (1154, token.Text.Whitespace, " "),
        (1155, token.Punctuation, "("),
        (1156, token.Text, "Message"),
        (1163, token.Punctuation, ")"),
        (1164, token.Punctuation, ";"),
        (1165, token.Text.Whitespace, " "),
        (1166, token.Comment, "-- §S-S-A-RD-V"),
        (1180, token.Text, "\n"),
        (1181, token.Text.Whitespace, "      "),
        (1187, token.Keyword, "transition"),
        (1197, token.Text, "\n"),
        (1198, token.Text.Whitespace, "         "),
        (1207, token.Keyword, "goto"),
        (1211, token.Text.Whitespace, " "),
        (1212, token.Text, "Process"),
        (1219, token.Text, "\n"),
        (1220, token.Text.Whitespace, "            "),
        (1232, token.Keyword, "if"),
        (1234, token.Text.Whitespace, " "),
        (1235, token.Text, "Message"),
        (1242, token.Punctuation, "'"),
        (1243, token.Keyword, "Valid"),
        (1248, token.Text.Whitespace, " "),
        (1249, token.Comment, "-- §S-S-T-VAT, §S-E-AT-V-V"),
        (1275, token.Text, "\n"),
        (1276, token.Text.Whitespace, "               "),
        (1291, token.Operator.Text, "and"),
        (1294, token.Text.Whitespace, " "),
        (1295, token.Text, "Message"),
        (1302, token.Punctuation, "."),
        (1303, token.Text, "Message_Type"),
        (1315, token.Text.Whitespace, " "),
        (1316, token.Operator, "="),
        (1317, token.Text.Whitespace, " "),
        (1318, token.Text, "Universal"),
        (1327, token.Punctuation, "::"),
        (1329, token.Text, "MT_Data"),
        (1336, token.Text.Whitespace, " "),
        (1337, token.Comment, "-- §S-S-T-S, §S-E-S-V, §S-S-T-L"),
        (1368, token.Text, "\n"),
        (1369, token.Text.Whitespace, "               "),
        (1384, token.Operator.Text, "and"),
        (1387, token.Text.Whitespace, " "),
        (1388, token.Text, "Message"),
        (1395, token.Punctuation, "."),
        (1396, token.Text, "Length"),
        (1402, token.Text.Whitespace, " "),
        (1403, token.Operator, "="),
        (1404, token.Text.Whitespace, " "),
        (1405, token.Literal.Number, "3"),
        (1406, token.Text.Whitespace, " "),
        (1407, token.Comment, "-- §S-S-T-S, §S-E-S-V, §S-S-T-L"),
        (1438, token.Text, "\n"),
        (1439, token.Text.Whitespace, "         "),
        (1448, token.Keyword, "goto"),
        (1452, token.Text.Whitespace, " "),
        (1453, token.Keyword, "null"),
        (1457, token.Text.Whitespace, " "),
        (1458, token.Comment, "-- §S-S-T-N"),
        (1469, token.Text, "\n"),
        (1470, token.Text.Whitespace, "      "),
        (1476, token.Keyword, "exception"),
        (1485, token.Text, "\n"),
        (1486, token.Text.Whitespace, "         "),
        (1495, token.Keyword, "goto"),
        (1499, token.Text.Whitespace, " "),
        (1500, token.Keyword, "null"),
        (1504, token.Text.Whitespace, " "),
        (1505, token.Comment, "-- §S-S-E"),
        (1514, token.Text, "\n"),
        (1515, token.Text.Whitespace, "      "),
        (1521, token.Keyword, "end"),
        (1524, token.Text.Whitespace, " "),
        (1525, token.Text, "Start"),
        (1530, token.Punctuation, ";"),
        (1531, token.Text, "\n\n"),
        (1533, token.Text.Whitespace, "      "),
        (1539, token.Keyword, "state"),
        (1544, token.Text.Whitespace, " "),
        (1545, token.Text, "Process"),
        (1552, token.Text.Whitespace, " "),
        (1553, token.Keyword, "is"),
        (1555, token.Text, "\n"),
        (1556, token.Text.Whitespace, "         "),
        (1565, token.Text, "Valid"),
        (1570, token.Text.Whitespace, " "),
        (1571, token.Punctuation, ":"),
        (1572, token.Text.Whitespace, " "),
        (1573, token.Text, "Result"),
        (1579, token.Punctuation, ";"),
        (1580, token.Text.Whitespace, " "),
        (1581, token.Comment, "-- §S-S-D-V-T-SC"),
        (1597, token.Text, "\n"),
        (1598, token.Text.Whitespace, "         "),
        (1607, token.Text, "Message_Type"),
        (1619, token.Text.Whitespace, " "),
        (1620, token.Punctuation, ":"),
        (1621, token.Text.Whitespace, " "),
        (1622, token.Text, "Universal"),
        (1631, token.Punctuation, "::"),
        (1633, token.Text, "Option_Type"),
        (1644, token.Punctuation, ";"),
        (1645, token.Text.Whitespace, " "),
        (1646, token.Comment, "-- §S-S-D-V-T-SC, §S-S-D-V-E-N"),
        (1676, token.Text, "\n"),
        (1677, token.Text.Whitespace, "         "),
        (1686, token.Text, "Length"),
        (1692, token.Text.Whitespace, " "),
        (1693, token.Punctuation, ":"),
        (1694, token.Text.Whitespace, " "),
        (1695, token.Text, "Length"),
        (1701, token.Punctuation, ";"),
        (1702, token.Text, "\n"),
        (1703, token.Text.Whitespace, "      "),
        (1709, token.Keyword, "begin"),
        (1714, token.Text, "\n"),
        (1715, token.Text.Whitespace, "         "),
        (1724, token.Text, "Message_Type"),
        (1736, token.Text.Whitespace, " "),
        (1737, token.Operator, ":="),
        (1739, token.Text.Whitespace, " "),
        (1740, token.Text, "Get_Message_Type"),
        (1756, token.Punctuation, ";"),
        (1757, token.Text.Whitespace, " "),
        (1758, token.Comment, "-- §S-S-A-A-CL, §S-E-CL-N"),
        (1783, token.Text, "\n"),
        (1784, token.Text.Whitespace, "         "),
        (1793, token.Text, "Valid"),
        (1798, token.Text.Whitespace, " "),
        (1799, token.Operator, ":="),
        (1801, token.Text.Whitespace, " "),
        (1802, token.Text, "Valid_Message"),
        (1815, token.Text.Whitespace, " "),
        (1816, token.Punctuation, "("),
        (1817, token.Text, "Message_Type"),
        (1829, token.Punctuation, ","),
        (1830, token.Text.Whitespace, " "),
        (1831, token.Text, "True"),
        (1835, token.Punctuation, ")"),
        (1836, token.Punctuation, ";"),
        (1837, token.Text.Whitespace, " "),
        (1838, token.Comment, "-- §S-S-A-A-CL, §S-E-CL-L"),
        (1863, token.Text, "\n"),
        (1864, token.Text.Whitespace, "         "),
        (1873, token.Text, "Length"),
        (1879, token.Text.Whitespace, " "),
        (1880, token.Operator, ":="),
        (1882, token.Text.Whitespace, " "),
        (1883, token.Text, "Message"),
        (1890, token.Punctuation, "."),
        (1891, token.Text, "Data"),
        (1895, token.Punctuation, "'"),
        (1896, token.Keyword, "Size"),
        (1900, token.Text.Whitespace, " "),
        (1901, token.Operator, "/"),
        (1902, token.Text.Whitespace, " "),
        (1903, token.Text, "Byte_Size"),
        (1912, token.Punctuation, ";"),
        (1913, token.Text.Whitespace, " "),
        (1914, token.Comment, "-- §S-S-A-A-ME"),
        (1928, token.Text, "\n"),
        (1929, token.Text.Whitespace, "         "),
        (1938, token.Comment, "-- §S-S-A-A-CL, §S-E-CL-V, §S-E-CL-S"),
        (1974, token.Text, "\n"),
        (1975, token.Text.Whitespace, "         "),
        (1984, token.Text, "Definite_Message"),
        (2000, token.Text.Whitespace, " "),
        (2001, token.Operator, ":="),
        (2003, token.Text.Whitespace, " "),
        (2004, token.Text, "Create_Message"),
        (2018, token.Text.Whitespace, " "),
        (2019, token.Punctuation, "("),
        (2020, token.Text, "Message_Type"),
        (2032, token.Punctuation, ","),
        (2033, token.Text.Whitespace, " "),
        (2034, token.Text, "Length"),
        (2040, token.Punctuation, ","),
        (2041, token.Text.Whitespace, " "),
        (2042, token.Text, "Message"),
        (2049, token.Punctuation, "."),
        (2050, token.Text, "Data"),
        (2054, token.Punctuation, ")"),
        (2055, token.Punctuation, ";"),
        (2056, token.Text, "\n"),
        (2057, token.Text.Whitespace, "      "),
        (2063, token.Keyword, "transition"),
        (2073, token.Text, "\n"),
        (2074, token.Text.Whitespace, "         "),
        (2083, token.Keyword, "goto"),
        (2087, token.Text.Whitespace, " "),
        (2088, token.Text, "Reply"),
        (2093, token.Text, "\n"),
        (2094, token.Text.Whitespace, "            "),
        (2106, token.Keyword, "if"),
        (2108, token.Text.Whitespace, " "),
        (2109, token.Text, "Valid"),
        (2114, token.Text.Whitespace, " "),
        (2115, token.Operator, "="),
        (2116, token.Text.Whitespace, " "),
        (2117, token.Text, "M_Valid"),
        (2124, token.Text.Whitespace, " "),
        (2125, token.Comment, "-- §S-S-T-BE"),
        (2137, token.Text, "\n"),
        (2138, token.Text.Whitespace, "         "),
        (2147, token.Keyword, "goto"),
        (2151, token.Text.Whitespace, " "),
        (2152, token.Keyword, "null"),
        (2156, token.Text.Whitespace, " "),
        (2157, token.Comment, "-- §S-S-T-N"),
        (2168, token.Text, "\n"),
        (2169, token.Text.Whitespace, "      "),
        (2175, token.Keyword, "exception"),
        (2184, token.Text, "\n"),
        (2185, token.Text.Whitespace, "         "),
        (2194, token.Keyword, "goto"),
        (2198, token.Text.Whitespace, " "),
        (2199, token.Keyword, "null"),
        (2203, token.Text.Whitespace, " "),
        (2204, token.Comment, "-- §S-S-E"),
        (2213, token.Text, "\n"),
        (2214, token.Text.Whitespace, "      "),
        (2220, token.Keyword, "end"),
        (2223, token.Text.Whitespace, " "),
        (2224, token.Text, "Process"),
        (2231, token.Punctuation, ";"),
        (2232, token.Text, "\n\n"),
        (2234, token.Text.Whitespace, "      "),
        (2240, token.Keyword, "state"),
        (2245, token.Text.Whitespace, " "),
        (2246, token.Text, "Reply"),
        (2251, token.Text.Whitespace, " "),
        (2252, token.Keyword, "is"),
        (2254, token.Text, "\n"),
        (2255, token.Text.Whitespace, "      "),
        (2261, token.Keyword, "begin"),
        (2266, token.Text, "\n"),
        (2267, token.Text.Whitespace, "         "),
        (2276, token.Keyword, "Channel"),
        (2283, token.Punctuation, "'"),
        (2284, token.Keyword, "Write"),
        (2289, token.Text.Whitespace, " "),
        (2290, token.Punctuation, "("),
        (2291, token.Text, "Definite_Message"),
        (2307, token.Punctuation, ")"),
        (2308, token.Punctuation, ";"),
        (2309, token.Text.Whitespace, " "),
        (2310, token.Comment, "-- §S-S-A-WR-V"),
        (2324, token.Text, "\n"),
        (2325, token.Text.Whitespace, "      "),
        (2331, token.Keyword, "transition"),
        (2341, token.Text, "\n"),
        (2342, token.Text.Whitespace, "         "),
        (2351, token.Keyword, "goto"),
        (2355, token.Text.Whitespace, " "),
        (2356, token.Text, "Process_2"),
        (2365, token.Text.Whitespace, " "),
        (2366, token.Comment, "-- §S-S-T-N"),
        (2377, token.Text, "\n"),
        (2378, token.Text.Whitespace, "      "),
        (2384, token.Keyword, "end"),
        (2387, token.Text.Whitespace, " "),
        (2388, token.Text, "Reply"),
        (2393, token.Punctuation, ";"),
        (2394, token.Text, "\n\n"),
        (2396, token.Text.Whitespace, "      "),
        (2402, token.Keyword, "state"),
        (2407, token.Text.Whitespace, " "),
        (2408, token.Text, "Process_2"),
        (2417, token.Text.Whitespace, " "),
        (2418, token.Keyword, "is"),
        (2420, token.Text, "\n"),
        (2421, token.Text.Whitespace, "         "),
        (2430, token.Text, "Length"),
        (2436, token.Text.Whitespace, " "),
        (2437, token.Punctuation, ":"),
        (2438, token.Text.Whitespace, " "),
        (2439, token.Text, "Length"),
        (2445, token.Punctuation, ";"),
        (2446, token.Text, "\n"),
        (2447, token.Text.Whitespace, "      "),
        (2453, token.Keyword, "begin"),
        (2458, token.Text, "\n"),
        (2459, token.Text.Whitespace, "         "),
        (2468, token.Text, "Length"),
        (2474, token.Text.Whitespace, " "),
        (2475, token.Operator, ":="),
        (2477, token.Text.Whitespace, " "),
        (2478, token.Text, "Message"),
        (2485, token.Punctuation, "'"),
        (2486, token.Keyword, "Size"),
        (2490, token.Text.Whitespace, " "),
        (2491, token.Operator, "/"),
        (2492, token.Text.Whitespace, " "),
        (2493, token.Literal.Number, "8"),
        (2494, token.Punctuation, ";"),
        (2495, token.Text.Whitespace, " "),
        (2496, token.Comment, "-- §S-S-A-A-ME"),
        (2510, token.Text, "\n"),
        (2511, token.Text.Whitespace, "         "),
        (2520, token.Comment, "-- §S-S-A-A-CL, §S-E-CL-L, §S-E-CL-V, §S-E-CL-OAT"),
        (2569, token.Text, "\n"),
        (2570, token.Text.Whitespace, "         "),
        (2579, token.Text, "Definite_Message"),
        (2595, token.Text.Whitespace, " "),
        (2596, token.Operator, ":="),
        (2598, token.Text.Whitespace, " "),
        (2599, token.Text, "Create_Message"),
        (2613, token.Text.Whitespace, " "),
        (2614, token.Punctuation, "("),
        (2615, token.Text, "Universal"),
        (2624, token.Punctuation, "::"),
        (2626, token.Text, "OT_Data"),
        (2633, token.Punctuation, ","),
        (2634, token.Text.Whitespace, " "),
        (2635, token.Text, "Length"),
        (2641, token.Punctuation, ","),
        (2642, token.Text.Whitespace, " "),
        (2643, token.Text, "Message"),
        (2650, token.Punctuation, "'"),
        (2651, token.Keyword, "Opaque"),
        (2657, token.Punctuation, ")"),
        (2658, token.Punctuation, ";"),
        (2659, token.Text, "\n"),
        (2660, token.Text.Whitespace, "      "),
        (2666, token.Keyword, "transition"),
        (2676, token.Text, "\n"),
        (2677, token.Text.Whitespace, "         "),
        (2686, token.Keyword, "goto"),
        (2690, token.Text.Whitespace, " "),
        (2691, token.Text, "Reply_2"),
        (2698, token.Text.Whitespace, " "),
        (2699, token.Comment, "-- §S-S-T-N"),
        (2710, token.Text, "\n"),
        (2711, token.Text.Whitespace, "      "),
        (2717, token.Keyword, "exception"),
        (2726, token.Text, "\n"),
        (2727, token.Text.Whitespace, "         "),
        (2736, token.Keyword, "goto"),
        (2740, token.Text.Whitespace, " "),
        (2741, token.Keyword, "null"),
        (2745, token.Text.Whitespace, " "),
        (2746, token.Comment, "-- §S-S-E"),
        (2755, token.Text, "\n"),
        (2756, token.Text.Whitespace, "      "),
        (2762, token.Keyword, "end"),
        (2765, token.Text.Whitespace, " "),
        (2766, token.Text, "Process_2"),
        (2775, token.Punctuation, ";"),
        (2776, token.Text, "\n\n"),
        (2778, token.Text.Whitespace, "      "),
        (2784, token.Keyword, "state"),
        (2789, token.Text.Whitespace, " "),
        (2790, token.Text, "Reply_2"),
        (2797, token.Text.Whitespace, " "),
        (2798, token.Keyword, "is"),
        (2800, token.Text, "\n"),
        (2801, token.Text.Whitespace, "      "),
        (2807, token.Keyword, "begin"),
        (2812, token.Text, "\n"),
        (2813, token.Text.Whitespace, "         "),
        (2822, token.Keyword, "Channel"),
        (2829, token.Punctuation, "'"),
        (2830, token.Keyword, "Write"),
        (2835, token.Text.Whitespace, " "),
        (2836, token.Punctuation, "("),
        (2837, token.Text, "Definite_Message"),
        (2853, token.Punctuation, ")"),
        (2854, token.Punctuation, ";"),
        (2855, token.Text.Whitespace, " "),
        (2856, token.Comment, "-- §S-S-A-WR-V"),
        (2870, token.Text, "\n"),
        (2871, token.Text.Whitespace, "      "),
        (2877, token.Keyword, "transition"),
        (2887, token.Text, "\n"),
        (2888, token.Text.Whitespace, "         "),
        (2897, token.Keyword, "goto"),
        (2901, token.Text.Whitespace, " "),
        (2902, token.Text, "Process_3"),
        (2911, token.Text.Whitespace, " "),
        (2912, token.Comment, "-- §S-S-T-N"),
        (2923, token.Text, "\n"),
        (2924, token.Text.Whitespace, "      "),
        (2930, token.Keyword, "end"),
        (2933, token.Text.Whitespace, " "),
        (2934, token.Text, "Reply_2"),
        (2941, token.Punctuation, ";"),
        (2942, token.Text, "\n\n"),
        (2944, token.Text.Whitespace, "      "),
        (2950, token.Keyword, "state"),
        (2955, token.Text.Whitespace, " "),
        (2956, token.Text, "Process_3"),
        (2965, token.Text.Whitespace, " "),
        (2966, token.Keyword, "is"),
        (2968, token.Text, "\n"),
        (2969, token.Text.Whitespace, "         "),
        (2978, token.Text, "Local_Message"),
        (2991, token.Text.Whitespace, " "),
        (2992, token.Punctuation, ":"),
        (2993, token.Text.Whitespace, " "),
        (2994, token.Text, "Definite_Message"),
        (3010, token.Punctuation, ";"),
        (3011, token.Text, "\n"),
        (3012, token.Text.Whitespace, "      "),
        (3018, token.Keyword, "begin"),
        (3023, token.Text, "\n"),
        (3024, token.Text.Whitespace, "         "),
        (3033, token.Comment, "-- §S-S-A-A-CL, §S-E-CL-L, §S-E-CL-A"),
        (3069, token.Text, "\n"),
        (3070, token.Text.Whitespace, "         "),
        (3079, token.Text, "Local_Message"),
        (3092, token.Text.Whitespace, " "),
        (3093, token.Operator, ":="),
        (3095, token.Text.Whitespace, " "),
        (3096, token.Text, "Create_Message"),
        (3110, token.Text.Whitespace, " "),
        (3111, token.Punctuation, "("),
        (3112, token.Text, "Universal"),
        (3121, token.Punctuation, "::"),
        (3123, token.Text, "OT_Data"),
        (3130, token.Punctuation, ","),
        (3131, token.Text.Whitespace, " "),
        (3132, token.Literal.Number, "2"),
        (3133, token.Punctuation, ","),
        (3134, token.Text.Whitespace, " "),
        (3135, token.Punctuation, "["),
        (3136, token.Literal.Number, "3"),
        (3137, token.Punctuation, ","),
        (3138, token.Text.Whitespace, " "),
        (3139, token.Literal.Number, "4"),
        (3140, token.Punctuation, "]"),
        (3141, token.Punctuation, ")"),
        (3142, token.Punctuation, ";"),
        (3143, token.Text, "\n"),
        (3144, token.Text.Whitespace, "         "),
        (3153, token.Comment, "-- §S-S-A-MFA-S"),
        (3168, token.Text, "\n"),
        (3169, token.Text.Whitespace, "         "),
        (3178, token.Text, "Definite_Message"),
        (3194, token.Punctuation, "."),
        (3195, token.Text, "Length"),
        (3201, token.Text.Whitespace, " "),
        (3202, token.Operator, ":="),
        (3204, token.Text.Whitespace, " "),
        (3205, token.Text, "Local_Message"),
        (3218, token.Punctuation, "."),
        (3219, token.Text, "Length"),
        (3225, token.Punctuation, ";"),
        (3226, token.Text, "\n"),
        (3227, token.Text.Whitespace, "         "),
        (3236, token.Comment, "-- §S-S-A-MFA-S"),
        (3251, token.Text, "\n"),
        (3252, token.Text.Whitespace, "         "),
        (3261, token.Text, "Definite_Message"),
        (3277, token.Punctuation, "."),
        (3278, token.Text, "Data"),
        (3282, token.Text.Whitespace, " "),
        (3283, token.Operator, ":="),
        (3285, token.Text.Whitespace, " "),
        (3286, token.Text, "Local_Message"),
        (3299, token.Punctuation, "."),
        (3300, token.Text, "Data"),
        (3304, token.Punctuation, ";"),
        (3305, token.Text, "\n"),
        (3306, token.Text.Whitespace, "      "),
        (3312, token.Keyword, "transition"),
        (3322, token.Text, "\n"),
        (3323, token.Text.Whitespace, "         "),
        (3332, token.Keyword, "goto"),
        (3336, token.Text.Whitespace, " "),
        (3337, token.Text, "Reply_3"),
        (3344, token.Text.Whitespace, " "),
        (3345, token.Comment, "-- §S-S-T-N"),
        (3356, token.Text, "\n"),
        (3357, token.Text.Whitespace, "      "),
        (3363, token.Keyword, "exception"),
        (3372, token.Text, "\n"),
        (3373, token.Text.Whitespace, "         "),
        (3382, token.Keyword, "goto"),
        (3386, token.Text.Whitespace, " "),
        (3387, token.Keyword, "null"),
        (3391, token.Text.Whitespace, " "),
        (3392, token.Comment, "-- §S-S-E"),
        (3401, token.Text, "\n"),
        (3402, token.Text.Whitespace, "      "),
        (3408, token.Keyword, "end"),
        (3411, token.Text.Whitespace, " "),
        (3412, token.Text, "Process_3"),
        (3421, token.Punctuation, ";"),
        (3422, token.Text, "\n\n"),
        (3424, token.Text.Whitespace, "      "),
        (3430, token.Keyword, "state"),
        (3435, token.Text.Whitespace, " "),
        (3436, token.Text, "Reply_3"),
        (3443, token.Text.Whitespace, " "),
        (3444, token.Keyword, "is"),
        (3446, token.Text, "\n"),
        (3447, token.Text.Whitespace, "      "),
        (3453, token.Keyword, "begin"),
        (3458, token.Text, "\n"),
        (3459, token.Text.Whitespace, "         "),
        (3468, token.Keyword, "Channel"),
        (3475, token.Punctuation, "'"),
        (3476, token.Keyword, "Write"),
        (3481, token.Text.Whitespace, " "),
        (3482, token.Punctuation, "("),
        (3483, token.Text, "Definite_Message"),
        (3499, token.Punctuation, ")"),
        (3500, token.Punctuation, ";"),
        (3501, token.Text.Whitespace, " "),
        (3502, token.Comment, "-- §S-S-A-WR-V"),
        (3516, token.Text, "\n"),
        (3517, token.Text.Whitespace, "      "),
        (3523, token.Keyword, "transition"),
        (3533, token.Text, "\n"),
        (3534, token.Text.Whitespace, "         "),
        (3543, token.Keyword, "goto"),
        (3547, token.Text.Whitespace, " "),
        (3548, token.Keyword, "null"),
        (3552, token.Text.Whitespace, " "),
        (3553, token.Comment, "-- §S-S-T-N"),
        (3564, token.Text, "\n"),
        (3565, token.Text.Whitespace, "      "),
        (3571, token.Keyword, "end"),
        (3574, token.Text.Whitespace, " "),
        (3575, token.Text, "Reply_3"),
        (3582, token.Punctuation, ";"),
        (3583, token.Text, "\n"),
        (3584, token.Text.Whitespace, "   "),
        (3587, token.Keyword, "end"),
        (3590, token.Text.Whitespace, " "),
        (3591, token.Text, "S"),
        (3592, token.Punctuation, ";"),
        (3593, token.Text, "\n\n"),
        (3595, token.Keyword, "end"),
        (3598, token.Text.Whitespace, " "),
        (3599, token.Text, "Test"),
        (3603, token.Punctuation, ";"),
        (3604, token.Text, "\n"),
    ]


def test_fragment_tokenization() -> None:
    lexer = tools.rflxlexer.RFLXLexer()
    tokens = list(lexer.get_tokens_unprocessed("type T is range 5 .. 127 with Size => 8"))

    assert tokens == [
        (0, token.Keyword, "type"),
        (4, token.Text.Whitespace, " "),
        (5, token.Text, "T"),
        (6, token.Text.Whitespace, " "),
        (7, token.Keyword, "is"),
        (9, token.Text.Whitespace, " "),
        (10, token.Keyword, "range"),
        (15, token.Text.Whitespace, " "),
        (16, token.Literal.Number, "5"),
        (17, token.Text.Whitespace, " "),
        (18, token.Operator, ".."),
        (20, token.Text.Whitespace, " "),
        (21, token.Literal.Number, "127"),
        (24, token.Text.Whitespace, " "),
        (25, token.Keyword, "with"),
        (29, token.Text.Whitespace, " "),
        (30, token.Text, "Size"),
        (34, token.Text.Whitespace, " "),
        (35, token.Operator, "=>"),
        (37, token.Text.Whitespace, " "),
        (38, token.Literal.Number, "8"),
    ]
