import pytest
from pygments import token

import tools.rflxlexer
from rflx.error import RecordFluxError
from tests.const import FEATURE_DIR

# ruff: noqa: SLF001


def test_calculate_offset_valid() -> None:
    assert tools.rflxlexer._calculate_offset("a", 1, 1) == 0
    assert tools.rflxlexer._calculate_offset("abc", 1, 2) == 1
    assert tools.rflxlexer._calculate_offset("abc\ndef", 2, 2) == 5
    assert tools.rflxlexer._calculate_offset("abc\n\ndef", 3, 2) == 6


def test_calculate_offset_invalid() -> None:
    with pytest.raises(RecordFluxError, match="^<stdin>:2:1: parser: error: line out of range$"):
        tools.rflxlexer._calculate_offset("", 2, 1)

    with pytest.raises(RecordFluxError, match="^<stdin>:2:4: parser: error: column out of range$"):
        tools.rflxlexer._calculate_offset("1234232\n1", 2, 4)


def test_message_tokenization() -> None:
    lexer = tools.rflxlexer.RFLXLexer()
    with (FEATURE_DIR / "shared" / "universal.rflx").open(encoding="utf-8") as f:
        tokens = list(lexer.get_tokens_unprocessed(f.read()))

    assert tokens == [
        (0, token.Keyword, "package"),
        (7, token.Text.Whitespace, " "),
        (8, token.Text, "Universal"),
        (17, token.Text.Whitespace, " "),
        (18, token.Keyword, "is"),
        (20, token.Text, "\n\n"),
        (22, token.Text.Whitespace, "   "),
        (25, token.Keyword, "type"),
        (29, token.Text.Whitespace, " "),
        (30, token.Text, "Message_Type"),
        (42, token.Text.Whitespace, " "),
        (43, token.Keyword, "is"),
        (45, token.Text.Whitespace, " "),
        (46, token.Punctuation, "("),
        (47, token.Text, "MT_Null"),
        (54, token.Text.Whitespace, " "),
        (55, token.Operator, "=>"),
        (57, token.Text.Whitespace, " "),
        (58, token.Literal.Number, "0"),
        (59, token.Punctuation, ","),
        (60, token.Text, "\n"),
        (61, token.Text.Whitespace, "                         "),
        (86, token.Text, "MT_Data"),
        (93, token.Text.Whitespace, " "),
        (94, token.Operator, "=>"),
        (96, token.Text.Whitespace, " "),
        (97, token.Literal.Number, "1"),
        (98, token.Punctuation, ","),
        (99, token.Text, "\n"),
        (100, token.Text.Whitespace, "                         "),
        (125, token.Text, "MT_Value"),
        (133, token.Text.Whitespace, " "),
        (134, token.Operator, "=>"),
        (136, token.Text.Whitespace, " "),
        (137, token.Literal.Number, "2"),
        (138, token.Punctuation, ","),
        (139, token.Text, "\n"),
        (140, token.Text.Whitespace, "                         "),
        (165, token.Text, "MT_Values"),
        (174, token.Text.Whitespace, " "),
        (175, token.Operator, "=>"),
        (177, token.Text.Whitespace, " "),
        (178, token.Literal.Number, "3"),
        (179, token.Punctuation, ","),
        (180, token.Text, "\n"),
        (181, token.Text.Whitespace, "                         "),
        (206, token.Text, "MT_Option_Types"),
        (221, token.Text.Whitespace, " "),
        (222, token.Operator, "=>"),
        (224, token.Text.Whitespace, " "),
        (225, token.Literal.Number, "4"),
        (226, token.Punctuation, ","),
        (227, token.Text, "\n"),
        (228, token.Text.Whitespace, "                         "),
        (253, token.Text, "MT_Options"),
        (263, token.Text.Whitespace, " "),
        (264, token.Operator, "=>"),
        (266, token.Text.Whitespace, " "),
        (267, token.Literal.Number, "5"),
        (268, token.Punctuation, ","),
        (269, token.Text, "\n"),
        (270, token.Text.Whitespace, "                         "),
        (295, token.Text, "MT_Unconstrained_Data"),
        (316, token.Text.Whitespace, " "),
        (317, token.Operator, "=>"),
        (319, token.Text.Whitespace, " "),
        (320, token.Literal.Number, "6"),
        (321, token.Punctuation, ","),
        (322, token.Text, "\n"),
        (323, token.Text.Whitespace, "                         "),
        (348, token.Text, "MT_Unconstrained_Options"),
        (372, token.Text.Whitespace, " "),
        (373, token.Operator, "=>"),
        (375, token.Text.Whitespace, " "),
        (376, token.Literal.Number, "7"),
        (377, token.Punctuation, ")"),
        (378, token.Text.Whitespace, " "),
        (379, token.Keyword, "with"),
        (383, token.Text.Whitespace, " "),
        (384, token.Text, "Size"),
        (388, token.Text.Whitespace, " "),
        (389, token.Operator, "=>"),
        (391, token.Text.Whitespace, " "),
        (392, token.Literal.Number, "8"),
        (393, token.Punctuation, ";"),
        (394, token.Text, "\n\n"),
        (396, token.Text.Whitespace, "   "),
        (399, token.Keyword, "type"),
        (403, token.Text.Whitespace, " "),
        (404, token.Text, "Length"),
        (410, token.Text.Whitespace, " "),
        (411, token.Keyword, "is"),
        (413, token.Text.Whitespace, " "),
        (414, token.Keyword, "range"),
        (419, token.Text.Whitespace, " "),
        (420, token.Literal.Number, "0"),
        (421, token.Text.Whitespace, " "),
        (422, token.Operator, ".."),
        (424, token.Text.Whitespace, " "),
        (425, token.Literal.Number, "2"),
        (426, token.Text.Whitespace, " "),
        (427, token.Operator, "**"),
        (429, token.Text.Whitespace, " "),
        (430, token.Literal.Number, "16"),
        (432, token.Text.Whitespace, " "),
        (433, token.Operator, "-"),
        (434, token.Text.Whitespace, " "),
        (435, token.Literal.Number, "1"),
        (436, token.Text.Whitespace, " "),
        (437, token.Keyword, "with"),
        (441, token.Text.Whitespace, " "),
        (442, token.Text, "Size"),
        (446, token.Text.Whitespace, " "),
        (447, token.Operator, "=>"),
        (449, token.Text.Whitespace, " "),
        (450, token.Literal.Number, "16"),
        (452, token.Punctuation, ";"),
        (453, token.Text, "\n\n"),
        (455, token.Text.Whitespace, "   "),
        (458, token.Keyword, "type"),
        (462, token.Text.Whitespace, " "),
        (463, token.Text, "Value"),
        (468, token.Text.Whitespace, " "),
        (469, token.Keyword, "is"),
        (471, token.Text.Whitespace, " "),
        (472, token.Keyword, "range"),
        (477, token.Text.Whitespace, " "),
        (478, token.Literal.Number, "0"),
        (479, token.Text.Whitespace, " "),
        (480, token.Operator, ".."),
        (482, token.Text.Whitespace, " "),
        (483, token.Literal.Number, "255"),
        (486, token.Text.Whitespace, " "),
        (487, token.Keyword, "with"),
        (491, token.Text.Whitespace, " "),
        (492, token.Text, "Size"),
        (496, token.Text.Whitespace, " "),
        (497, token.Operator, "=>"),
        (499, token.Text.Whitespace, " "),
        (500, token.Literal.Number, "8"),
        (501, token.Punctuation, ";"),
        (502, token.Text, "\n\n"),
        (504, token.Text.Whitespace, "   "),
        (507, token.Keyword, "type"),
        (511, token.Text.Whitespace, " "),
        (512, token.Text, "Values"),
        (518, token.Text.Whitespace, " "),
        (519, token.Keyword, "is"),
        (521, token.Text.Whitespace, " "),
        (522, token.Keyword, "sequence"),
        (530, token.Text.Whitespace, " "),
        (531, token.Keyword, "of"),
        (533, token.Text.Whitespace, " "),
        (534, token.Text, "Value"),
        (539, token.Punctuation, ";"),
        (540, token.Text, "\n\n"),
        (542, token.Text.Whitespace, "   "),
        (545, token.Keyword, "type"),
        (549, token.Text.Whitespace, " "),
        (550, token.Text, "Option_Type"),
        (561, token.Text.Whitespace, " "),
        (562, token.Keyword, "is"),
        (564, token.Text.Whitespace, " "),
        (565, token.Punctuation, "("),
        (566, token.Text, "OT_Null"),
        (573, token.Text.Whitespace, " "),
        (574, token.Operator, "=>"),
        (576, token.Text.Whitespace, " "),
        (577, token.Literal.Number, "0"),
        (578, token.Punctuation, ","),
        (579, token.Text.Whitespace, " "),
        (580, token.Text, "OT_Data"),
        (587, token.Text.Whitespace, " "),
        (588, token.Operator, "=>"),
        (590, token.Text.Whitespace, " "),
        (591, token.Literal.Number, "1"),
        (592, token.Punctuation, ")"),
        (593, token.Text.Whitespace, " "),
        (594, token.Keyword, "with"),
        (598, token.Text.Whitespace, " "),
        (599, token.Text, "Size"),
        (603, token.Text.Whitespace, " "),
        (604, token.Operator, "=>"),
        (606, token.Text.Whitespace, " "),
        (607, token.Literal.Number, "8"),
        (608, token.Punctuation, ","),
        (609, token.Text.Whitespace, " "),
        (610, token.Text, "Always_Valid"),
        (622, token.Text.Whitespace, " "),
        (623, token.Operator, "=>"),
        (625, token.Text.Whitespace, " "),
        (626, token.Text, "True"),
        (630, token.Punctuation, ";"),
        (631, token.Text, "\n\n"),
        (633, token.Text.Whitespace, "   "),
        (636, token.Keyword, "type"),
        (640, token.Text.Whitespace, " "),
        (641, token.Text, "Option_Types"),
        (653, token.Text.Whitespace, " "),
        (654, token.Keyword, "is"),
        (656, token.Text.Whitespace, " "),
        (657, token.Keyword, "sequence"),
        (665, token.Text.Whitespace, " "),
        (666, token.Keyword, "of"),
        (668, token.Text.Whitespace, " "),
        (669, token.Text, "Option_Type"),
        (680, token.Punctuation, ";"),
        (681, token.Text, "\n\n"),
        (683, token.Text.Whitespace, "   "),
        (686, token.Keyword, "type"),
        (690, token.Text.Whitespace, " "),
        (691, token.Text, "Option"),
        (697, token.Text.Whitespace, " "),
        (698, token.Keyword, "is"),
        (700, token.Text, "\n"),
        (701, token.Text.Whitespace, "      "),
        (707, token.Keyword, "message"),
        (714, token.Text, "\n"),
        (715, token.Text.Whitespace, "         "),
        (724, token.Text, "Option_Type"),
        (735, token.Text.Whitespace, " "),
        (736, token.Punctuation, ":"),
        (737, token.Text.Whitespace, " "),
        (738, token.Text, "Option_Type"),
        (749, token.Text, "\n"),
        (750, token.Text.Whitespace, "            "),
        (762, token.Keyword, "then"),
        (766, token.Text.Whitespace, " "),
        (767, token.Keyword, "null"),
        (771, token.Text, "\n"),
        (772, token.Text.Whitespace, "               "),
        (787, token.Keyword, "if"),
        (789, token.Text.Whitespace, " "),
        (790, token.Text, "Option_Type"),
        (801, token.Text.Whitespace, " "),
        (802, token.Operator, "="),
        (803, token.Text.Whitespace, " "),
        (804, token.Text, "OT_Null"),
        (811, token.Text, "\n"),
        (812, token.Text.Whitespace, "            "),
        (824, token.Keyword, "then"),
        (828, token.Text.Whitespace, " "),
        (829, token.Text, "Length"),
        (835, token.Text, "\n"),
        (836, token.Text.Whitespace, "               "),
        (851, token.Keyword, "if"),
        (853, token.Text.Whitespace, " "),
        (854, token.Text, "Option_Type"),
        (865, token.Text.Whitespace, " "),
        (866, token.Operator, "="),
        (867, token.Text.Whitespace, " "),
        (868, token.Text, "OT_Data"),
        (875, token.Punctuation, ";"),
        (876, token.Text, "\n"),
        (877, token.Text.Whitespace, "         "),
        (886, token.Text, "Length"),
        (892, token.Text.Whitespace, " "),
        (893, token.Punctuation, ":"),
        (894, token.Text.Whitespace, " "),
        (895, token.Text, "Length"),
        (901, token.Text, "\n"),
        (902, token.Text.Whitespace, "            "),
        (914, token.Keyword, "then"),
        (918, token.Text.Whitespace, " "),
        (919, token.Text, "Data"),
        (923, token.Text, "\n"),
        (924, token.Text.Whitespace, "               "),
        (939, token.Keyword, "with"),
        (943, token.Text.Whitespace, " "),
        (944, token.Text, "Size"),
        (948, token.Text.Whitespace, " "),
        (949, token.Operator, "=>"),
        (951, token.Text.Whitespace, " "),
        (952, token.Text, "Length"),
        (958, token.Text.Whitespace, " "),
        (959, token.Operator, "*"),
        (960, token.Text.Whitespace, " "),
        (961, token.Literal.Number, "8"),
        (962, token.Punctuation, ";"),
        (963, token.Text, "\n"),
        (964, token.Text.Whitespace, "         "),
        (973, token.Text, "Data"),
        (977, token.Text.Whitespace, " "),
        (978, token.Punctuation, ":"),
        (979, token.Text.Whitespace, " "),
        (980, token.Text, "Opaque"),
        (986, token.Punctuation, ";"),
        (987, token.Text, "\n"),
        (988, token.Text.Whitespace, "      "),
        (994, token.Keyword, "end"),
        (997, token.Text.Whitespace, " "),
        (998, token.Keyword, "message"),
        (1005, token.Punctuation, ";"),
        (1006, token.Text, "\n\n"),
        (1008, token.Text.Whitespace, "   "),
        (1011, token.Keyword, "type"),
        (1015, token.Text.Whitespace, " "),
        (1016, token.Text, "Options"),
        (1023, token.Text.Whitespace, " "),
        (1024, token.Keyword, "is"),
        (1026, token.Text.Whitespace, " "),
        (1027, token.Keyword, "sequence"),
        (1035, token.Text.Whitespace, " "),
        (1036, token.Keyword, "of"),
        (1038, token.Text.Whitespace, " "),
        (1039, token.Text, "Option"),
        (1045, token.Punctuation, ";"),
        (1046, token.Text, "\n\n"),
        (1048, token.Text.Whitespace, "   "),
        (1051, token.Keyword, "type"),
        (1055, token.Text.Whitespace, " "),
        (1056, token.Text, "Message"),
        (1063, token.Text.Whitespace, " "),
        (1064, token.Keyword, "is"),
        (1066, token.Text, "\n"),
        (1067, token.Text.Whitespace, "      "),
        (1073, token.Keyword, "message"),
        (1080, token.Text, "\n"),
        (1081, token.Text.Whitespace, "         "),
        (1090, token.Text, "Message_Type"),
        (1102, token.Text.Whitespace, " "),
        (1103, token.Punctuation, ":"),
        (1104, token.Text.Whitespace, " "),
        (1105, token.Text, "Message_Type"),
        (1117, token.Text, "\n"),
        (1118, token.Text.Whitespace, "            "),
        (1130, token.Keyword, "then"),
        (1134, token.Text.Whitespace, " "),
        (1135, token.Keyword, "null"),
        (1139, token.Text, "\n"),
        (1140, token.Text.Whitespace, "               "),
        (1155, token.Keyword, "if"),
        (1157, token.Text.Whitespace, " "),
        (1158, token.Text, "Message_Type"),
        (1170, token.Text.Whitespace, " "),
        (1171, token.Operator, "="),
        (1172, token.Text.Whitespace, " "),
        (1173, token.Text, "MT_Null"),
        (1180, token.Text, "\n"),
        (1181, token.Text.Whitespace, "            "),
        (1193, token.Keyword, "then"),
        (1197, token.Text.Whitespace, " "),
        (1198, token.Text, "Data"),
        (1202, token.Text, "\n"),
        (1203, token.Text.Whitespace, "               "),
        (1218, token.Keyword, "with"),
        (1222, token.Text.Whitespace, " "),
        (1223, token.Text, "Size"),
        (1227, token.Text.Whitespace, " "),
        (1228, token.Operator, "=>"),
        (1230, token.Text.Whitespace, " "),
        (1231, token.Text, "Message"),
        (1238, token.Punctuation, "'"),
        (1239, token.Keyword, "Last"),
        (1243, token.Text.Whitespace, " "),
        (1244, token.Operator, "-"),
        (1245, token.Text.Whitespace, " "),
        (1246, token.Text, "Message_Type"),
        (1258, token.Punctuation, "'"),
        (1259, token.Keyword, "Last"),
        (1263, token.Text, "\n"),
        (1264, token.Text.Whitespace, "               "),
        (1279, token.Keyword, "if"),
        (1281, token.Text.Whitespace, " "),
        (1282, token.Text, "Message_Type"),
        (1294, token.Text.Whitespace, " "),
        (1295, token.Operator, "="),
        (1296, token.Text.Whitespace, " "),
        (1297, token.Text, "MT_Unconstrained_Data"),
        (1318, token.Text, "\n"),
        (1319, token.Text.Whitespace, "            "),
        (1331, token.Keyword, "then"),
        (1335, token.Text.Whitespace, " "),
        (1336, token.Text, "Length"),
        (1342, token.Text, "\n"),
        (1343, token.Text.Whitespace, "               "),
        (1358, token.Keyword, "if"),
        (1360, token.Text.Whitespace, " "),
        (1361, token.Text, "Message_Type"),
        (1373, token.Text.Whitespace, " "),
        (1374, token.Operator, "/="),
        (1376, token.Text.Whitespace, " "),
        (1377, token.Text, "MT_Null"),
        (1384, token.Text, "\n"),
        (1385, token.Text.Whitespace, "                  "),
        (1403, token.Operator.Text, "and"),
        (1406, token.Text.Whitespace, " "),
        (1407, token.Text, "Message_Type"),
        (1419, token.Text.Whitespace, " "),
        (1420, token.Operator, "/="),
        (1422, token.Text.Whitespace, " "),
        (1423, token.Text, "MT_Unconstrained_Data"),
        (1444, token.Text, "\n"),
        (1445, token.Text.Whitespace, "                  "),
        (1463, token.Operator.Text, "and"),
        (1466, token.Text.Whitespace, " "),
        (1467, token.Text, "Message_Type"),
        (1479, token.Text.Whitespace, " "),
        (1480, token.Operator, "/="),
        (1482, token.Text.Whitespace, " "),
        (1483, token.Text, "MT_Unconstrained_Options"),
        (1507, token.Text, "\n"),
        (1508, token.Text.Whitespace, "            "),
        (1520, token.Keyword, "then"),
        (1524, token.Text.Whitespace, " "),
        (1525, token.Text, "Options"),
        (1532, token.Text, "\n"),
        (1533, token.Text.Whitespace, "               "),
        (1548, token.Keyword, "with"),
        (1552, token.Text.Whitespace, " "),
        (1553, token.Text, "Size"),
        (1557, token.Text.Whitespace, " "),
        (1558, token.Operator, "=>"),
        (1560, token.Text.Whitespace, " "),
        (1561, token.Text, "Message"),
        (1568, token.Punctuation, "'"),
        (1569, token.Keyword, "Last"),
        (1573, token.Text.Whitespace, " "),
        (1574, token.Operator, "-"),
        (1575, token.Text.Whitespace, " "),
        (1576, token.Text, "Message_Type"),
        (1588, token.Punctuation, "'"),
        (1589, token.Keyword, "Last"),
        (1593, token.Text, "\n"),
        (1594, token.Text.Whitespace, "               "),
        (1609, token.Keyword, "if"),
        (1611, token.Text.Whitespace, " "),
        (1612, token.Text, "Message_Type"),
        (1624, token.Text.Whitespace, " "),
        (1625, token.Operator, "="),
        (1626, token.Text.Whitespace, " "),
        (1627, token.Text, "MT_Unconstrained_Options"),
        (1651, token.Punctuation, ";"),
        (1652, token.Text, "\n"),
        (1653, token.Text.Whitespace, "         "),
        (1662, token.Text, "Length"),
        (1668, token.Text.Whitespace, " "),
        (1669, token.Punctuation, ":"),
        (1670, token.Text.Whitespace, " "),
        (1671, token.Text, "Length"),
        (1677, token.Text, "\n"),
        (1678, token.Text.Whitespace, "            "),
        (1690, token.Keyword, "then"),
        (1694, token.Text.Whitespace, " "),
        (1695, token.Text, "Data"),
        (1699, token.Text, "\n"),
        (1700, token.Text.Whitespace, "               "),
        (1715, token.Keyword, "with"),
        (1719, token.Text.Whitespace, " "),
        (1720, token.Text, "Size"),
        (1724, token.Text.Whitespace, " "),
        (1725, token.Operator, "=>"),
        (1727, token.Text.Whitespace, " "),
        (1728, token.Text, "Length"),
        (1734, token.Text.Whitespace, " "),
        (1735, token.Operator, "*"),
        (1736, token.Text.Whitespace, " "),
        (1737, token.Literal.Number, "8"),
        (1738, token.Text, "\n"),
        (1739, token.Text.Whitespace, "               "),
        (1754, token.Keyword, "if"),
        (1756, token.Text.Whitespace, " "),
        (1757, token.Text, "Message_Type"),
        (1769, token.Text.Whitespace, " "),
        (1770, token.Operator, "="),
        (1771, token.Text.Whitespace, " "),
        (1772, token.Text, "MT_Data"),
        (1779, token.Text, "\n"),
        (1780, token.Text.Whitespace, "            "),
        (1792, token.Keyword, "then"),
        (1796, token.Text.Whitespace, " "),
        (1797, token.Text, "Option_Types"),
        (1809, token.Text, "\n"),
        (1810, token.Text.Whitespace, "               "),
        (1825, token.Keyword, "with"),
        (1829, token.Text.Whitespace, " "),
        (1830, token.Text, "Size"),
        (1834, token.Text.Whitespace, " "),
        (1835, token.Operator, "=>"),
        (1837, token.Text.Whitespace, " "),
        (1838, token.Text, "Length"),
        (1844, token.Text.Whitespace, " "),
        (1845, token.Operator, "*"),
        (1846, token.Text.Whitespace, " "),
        (1847, token.Literal.Number, "8"),
        (1848, token.Text, "\n"),
        (1849, token.Text.Whitespace, "               "),
        (1864, token.Keyword, "if"),
        (1866, token.Text.Whitespace, " "),
        (1867, token.Text, "Message_Type"),
        (1879, token.Text.Whitespace, " "),
        (1880, token.Operator, "="),
        (1881, token.Text.Whitespace, " "),
        (1882, token.Text, "MT_Option_Types"),
        (1897, token.Text, "\n"),
        (1898, token.Text.Whitespace, "            "),
        (1910, token.Keyword, "then"),
        (1914, token.Text.Whitespace, " "),
        (1915, token.Text, "Options"),
        (1922, token.Text, "\n"),
        (1923, token.Text.Whitespace, "               "),
        (1938, token.Keyword, "with"),
        (1942, token.Text.Whitespace, " "),
        (1943, token.Text, "Size"),
        (1947, token.Text.Whitespace, " "),
        (1948, token.Operator, "=>"),
        (1950, token.Text.Whitespace, " "),
        (1951, token.Text, "Length"),
        (1957, token.Text.Whitespace, " "),
        (1958, token.Operator, "*"),
        (1959, token.Text.Whitespace, " "),
        (1960, token.Literal.Number, "8"),
        (1961, token.Text, "\n"),
        (1962, token.Text.Whitespace, "               "),
        (1977, token.Keyword, "if"),
        (1979, token.Text.Whitespace, " "),
        (1980, token.Text, "Message_Type"),
        (1992, token.Text.Whitespace, " "),
        (1993, token.Operator, "="),
        (1994, token.Text.Whitespace, " "),
        (1995, token.Text, "MT_Options"),
        (2005, token.Text, "\n"),
        (2006, token.Text.Whitespace, "            "),
        (2018, token.Keyword, "then"),
        (2022, token.Text.Whitespace, " "),
        (2023, token.Text, "Value"),
        (2028, token.Text, "\n"),
        (2029, token.Text.Whitespace, "               "),
        (2044, token.Keyword, "if"),
        (2046, token.Text.Whitespace, " "),
        (2047, token.Text, "Message_Type"),
        (2059, token.Text.Whitespace, " "),
        (2060, token.Operator, "="),
        (2061, token.Text.Whitespace, " "),
        (2062, token.Text, "MT_Value"),
        (2070, token.Text, "\n"),
        (2071, token.Text.Whitespace, "                  "),
        (2089, token.Operator.Text, "and"),
        (2092, token.Text.Whitespace, " "),
        (2093, token.Text, "Length"),
        (2099, token.Text.Whitespace, " "),
        (2100, token.Operator, "="),
        (2101, token.Text.Whitespace, " "),
        (2102, token.Text, "Universal"),
        (2111, token.Punctuation, "::"),
        (2113, token.Text, "Value"),
        (2118, token.Punctuation, "'"),
        (2119, token.Keyword, "Size"),
        (2123, token.Text.Whitespace, " "),
        (2124, token.Operator, "/"),
        (2125, token.Text.Whitespace, " "),
        (2126, token.Literal.Number, "8"),
        (2127, token.Text, "\n"),
        (2128, token.Text.Whitespace, "            "),
        (2140, token.Keyword, "then"),
        (2144, token.Text.Whitespace, " "),
        (2145, token.Text, "Values"),
        (2151, token.Text, "\n"),
        (2152, token.Text.Whitespace, "               "),
        (2167, token.Keyword, "with"),
        (2171, token.Text.Whitespace, " "),
        (2172, token.Text, "Size"),
        (2176, token.Text.Whitespace, " "),
        (2177, token.Operator, "=>"),
        (2179, token.Text.Whitespace, " "),
        (2180, token.Text, "Length"),
        (2186, token.Text.Whitespace, " "),
        (2187, token.Operator, "*"),
        (2188, token.Text.Whitespace, " "),
        (2189, token.Literal.Number, "8"),
        (2190, token.Text, "\n"),
        (2191, token.Text.Whitespace, "               "),
        (2206, token.Keyword, "if"),
        (2208, token.Text.Whitespace, " "),
        (2209, token.Text, "Message_Type"),
        (2221, token.Text.Whitespace, " "),
        (2222, token.Operator, "="),
        (2223, token.Text.Whitespace, " "),
        (2224, token.Text, "MT_Values"),
        (2233, token.Punctuation, ";"),
        (2234, token.Text, "\n"),
        (2235, token.Text.Whitespace, "         "),
        (2244, token.Text, "Data"),
        (2248, token.Text.Whitespace, " "),
        (2249, token.Punctuation, ":"),
        (2250, token.Text.Whitespace, " "),
        (2251, token.Text, "Opaque"),
        (2257, token.Text, "\n"),
        (2258, token.Text.Whitespace, "            "),
        (2270, token.Keyword, "then"),
        (2274, token.Text.Whitespace, " "),
        (2275, token.Keyword, "null"),
        (2279, token.Punctuation, ";"),
        (2280, token.Text, "\n"),
        (2281, token.Text.Whitespace, "         "),
        (2290, token.Text, "Option_Types"),
        (2302, token.Text.Whitespace, " "),
        (2303, token.Punctuation, ":"),
        (2304, token.Text.Whitespace, " "),
        (2305, token.Text, "Option_Types"),
        (2317, token.Text, "\n"),
        (2318, token.Text.Whitespace, "            "),
        (2330, token.Keyword, "then"),
        (2334, token.Text.Whitespace, " "),
        (2335, token.Keyword, "null"),
        (2339, token.Punctuation, ";"),
        (2340, token.Text, "\n"),
        (2341, token.Text.Whitespace, "         "),
        (2350, token.Text, "Options"),
        (2357, token.Text.Whitespace, " "),
        (2358, token.Punctuation, ":"),
        (2359, token.Text.Whitespace, " "),
        (2360, token.Text, "Options"),
        (2367, token.Text, "\n"),
        (2368, token.Text.Whitespace, "            "),
        (2380, token.Keyword, "then"),
        (2384, token.Text.Whitespace, " "),
        (2385, token.Keyword, "null"),
        (2389, token.Punctuation, ";"),
        (2390, token.Text, "\n"),
        (2391, token.Text.Whitespace, "         "),
        (2400, token.Text, "Value"),
        (2405, token.Text.Whitespace, " "),
        (2406, token.Punctuation, ":"),
        (2407, token.Text.Whitespace, " "),
        (2408, token.Text, "Value"),
        (2413, token.Text, "\n"),
        (2414, token.Text.Whitespace, "            "),
        (2426, token.Keyword, "then"),
        (2430, token.Text.Whitespace, " "),
        (2431, token.Keyword, "null"),
        (2435, token.Punctuation, ";"),
        (2436, token.Text, "\n"),
        (2437, token.Text.Whitespace, "         "),
        (2446, token.Text, "Values"),
        (2452, token.Text.Whitespace, " "),
        (2453, token.Punctuation, ":"),
        (2454, token.Text.Whitespace, " "),
        (2455, token.Text, "Values"),
        (2461, token.Punctuation, ";"),
        (2462, token.Text, "\n"),
        (2463, token.Text.Whitespace, "      "),
        (2469, token.Keyword, "end"),
        (2472, token.Text.Whitespace, " "),
        (2473, token.Keyword, "message"),
        (2480, token.Punctuation, ";"),
        (2481, token.Text, "\n\n"),
        (2483, token.Text.Whitespace, "   "),
        (2486, token.Keyword, "for"),
        (2489, token.Text.Whitespace, " "),
        (2490, token.Text, "Message"),
        (2497, token.Text.Whitespace, " "),
        (2498, token.Keyword, "use"),
        (2501, token.Text.Whitespace, " "),
        (2502, token.Punctuation, "("),
        (2503, token.Text, "Data"),
        (2507, token.Text.Whitespace, " "),
        (2508, token.Operator, "=>"),
        (2510, token.Text.Whitespace, " "),
        (2511, token.Text, "Option"),
        (2517, token.Punctuation, ")"),
        (2518, token.Punctuation, ";"),
        (2519, token.Text, "\n\n"),
        (2521, token.Keyword, "end"),
        (2524, token.Text.Whitespace, " "),
        (2525, token.Text, "Universal"),
        (2534, token.Punctuation, ";"),
        (2535, token.Text, "\n"),
    ]


def test_session_tokenization() -> None:
    lexer = tools.rflxlexer.RFLXLexer()
    with (FEATURE_DIR / "session_functions" / "test.rflx").open(encoding="utf-8") as f:
        tokens = list(lexer.get_tokens_unprocessed(f.read()))

    assert tokens == [
        (0, token.Keyword, "with"),
        (4, token.Text.Whitespace, " "),
        (5, token.Text, "Universal"),
        (14, token.Punctuation, ";"),
        (15, token.Text, "\n\n"),
        (17, token.Keyword, "package"),
        (24, token.Text.Whitespace, " "),
        (25, token.Text, "Test"),
        (29, token.Text.Whitespace, " "),
        (30, token.Keyword, "is"),
        (32, token.Text, "\n\n"),
        (34, token.Text.Whitespace, "   "),
        (37, token.Keyword, "type"),
        (41, token.Text.Whitespace, " "),
        (42, token.Text, "Result"),
        (48, token.Text.Whitespace, " "),
        (49, token.Keyword, "is"),
        (51, token.Text.Whitespace, " "),
        (52, token.Punctuation, "("),
        (53, token.Text, "M_Valid"),
        (60, token.Punctuation, ","),
        (61, token.Text.Whitespace, " "),
        (62, token.Text, "M_Invalid"),
        (71, token.Punctuation, ")"),
        (72, token.Text.Whitespace, " "),
        (73, token.Keyword, "with"),
        (77, token.Text.Whitespace, " "),
        (78, token.Text, "Size"),
        (82, token.Text.Whitespace, " "),
        (83, token.Operator, "=>"),
        (85, token.Text.Whitespace, " "),
        (86, token.Literal.Number, "2"),
        (87, token.Punctuation, ";"),
        (88, token.Text, "\n\n"),
        (90, token.Text.Whitespace, "   "),
        (93, token.Keyword, "type"),
        (97, token.Text.Whitespace, " "),
        (98, token.Text, "Length"),
        (104, token.Text.Whitespace, " "),
        (105, token.Keyword, "is"),
        (107, token.Text.Whitespace, " "),
        (108, token.Keyword, "range"),
        (113, token.Text.Whitespace, " "),
        (114, token.Literal.Number, "0"),
        (115, token.Text.Whitespace, " "),
        (116, token.Operator, ".."),
        (118, token.Text.Whitespace, " "),
        (119, token.Literal.Number, "2"),
        (120, token.Text.Whitespace, " "),
        (121, token.Operator, "**"),
        (123, token.Text.Whitespace, " "),
        (124, token.Literal.Number, "8"),
        (125, token.Text.Whitespace, " "),
        (126, token.Operator, "-"),
        (127, token.Text.Whitespace, " "),
        (128, token.Literal.Number, "1"),
        (129, token.Text.Whitespace, " "),
        (130, token.Keyword, "with"),
        (134, token.Text.Whitespace, " "),
        (135, token.Text, "Size"),
        (139, token.Text.Whitespace, " "),
        (140, token.Operator, "=>"),
        (142, token.Text.Whitespace, " "),
        (143, token.Literal.Number, "8"),
        (144, token.Punctuation, ";"),
        (145, token.Text, "\n\n"),
        (147, token.Text.Whitespace, "   "),
        (150, token.Keyword, "type"),
        (154, token.Text.Whitespace, " "),
        (155, token.Text, "Definite_Message"),
        (171, token.Text.Whitespace, " "),
        (172, token.Keyword, "is"),
        (174, token.Text, "\n"),
        (175, token.Text.Whitespace, "      "),
        (181, token.Keyword, "message"),
        (188, token.Text, "\n"),
        (189, token.Text.Whitespace, "         "),
        (198, token.Text, "Message_Type"),
        (210, token.Text.Whitespace, " "),
        (211, token.Punctuation, ":"),
        (212, token.Text.Whitespace, " "),
        (213, token.Text, "Universal"),
        (222, token.Punctuation, "::"),
        (224, token.Text, "Option_Type"),
        (235, token.Punctuation, ";"),
        (236, token.Text, "\n"),
        (237, token.Text.Whitespace, "         "),
        (246, token.Text, "Length"),
        (252, token.Text.Whitespace, " "),
        (253, token.Punctuation, ":"),
        (254, token.Text.Whitespace, " "),
        (255, token.Text, "Length"),
        (261, token.Punctuation, ";"),
        (262, token.Text, "\n"),
        (263, token.Text.Whitespace, "         "),
        (272, token.Text, "Data"),
        (276, token.Text.Whitespace, " "),
        (277, token.Punctuation, ":"),
        (278, token.Text.Whitespace, " "),
        (279, token.Text, "Opaque"),
        (285, token.Text, "\n"),
        (286, token.Text.Whitespace, "            "),
        (298, token.Keyword, "with"),
        (302, token.Text.Whitespace, " "),
        (303, token.Text, "Size"),
        (307, token.Text.Whitespace, " "),
        (308, token.Operator, "=>"),
        (310, token.Text.Whitespace, " "),
        (311, token.Text, "Length"),
        (317, token.Text.Whitespace, " "),
        (318, token.Operator, "*"),
        (319, token.Text.Whitespace, " "),
        (320, token.Literal.Number, "8"),
        (321, token.Punctuation, ";"),
        (322, token.Text, "\n"),
        (323, token.Text.Whitespace, "      "),
        (329, token.Keyword, "end"),
        (332, token.Text.Whitespace, " "),
        (333, token.Keyword, "message"),
        (340, token.Punctuation, ";"),
        (341, token.Text, "\n\n"),
        (343, token.Text.Whitespace, "   "),
        (346, token.Keyword, "generic"),
        (353, token.Text, "\n"),
        (354, token.Text.Whitespace, "      "),
        (360, token.Keyword, "Channel"),
        (367, token.Text.Whitespace, " "),
        (368, token.Punctuation, ":"),
        (369, token.Text.Whitespace, " "),
        (370, token.Keyword, "Channel"),
        (377, token.Text.Whitespace, " "),
        (378, token.Keyword, "with"),
        (382, token.Text.Whitespace, " "),
        (383, token.Keyword, "Readable"),
        (391, token.Punctuation, ","),
        (392, token.Text.Whitespace, " "),
        (393, token.Keyword, "Writable"),
        (401, token.Punctuation, ";"),
        (402, token.Text.Whitespace, " "),
        (403, token.Comment, "-- §S-P-C-RW"),
        (415, token.Text, "\n"),
        (416, token.Text.Whitespace, "      "),
        (422, token.Comment, "-- §S-P-F-R-S"),
        (435, token.Text, "\n"),
        (436, token.Text.Whitespace, "      "),
        (442, token.Keyword, "with"),
        (446, token.Text.Whitespace, " "),
        (447, token.Keyword, "function"),
        (455, token.Text.Whitespace, " "),
        (456, token.Text, "Get_Message_Type"),
        (472, token.Text.Whitespace, " "),
        (473, token.Keyword, "return"),
        (479, token.Text.Whitespace, " "),
        (480, token.Text, "Universal"),
        (489, token.Punctuation, "::"),
        (491, token.Text, "Option_Type"),
        (502, token.Punctuation, ";"),
        (503, token.Text, "\n"),
        (504, token.Text.Whitespace, "      "),
        (510, token.Comment, "-- §S-P-F-P-S, §S-P-F-P-O, §S-P-F-R-M"),
        (547, token.Text, "\n"),
        (548, token.Text.Whitespace, "      "),
        (554, token.Keyword, "with"),
        (558, token.Text.Whitespace, " "),
        (559, token.Keyword, "function"),
        (567, token.Text.Whitespace, " "),
        (568, token.Text, "Create_Message"),
        (582, token.Text, "\n"),
        (583, token.Text.Whitespace, "         "),
        (592, token.Punctuation, "("),
        (593, token.Text, "Message_Type"),
        (605, token.Text.Whitespace, " "),
        (606, token.Punctuation, ":"),
        (607, token.Text.Whitespace, " "),
        (608, token.Text, "Universal"),
        (617, token.Punctuation, "::"),
        (619, token.Text, "Option_Type"),
        (630, token.Punctuation, ";"),
        (631, token.Text, "\n"),
        (632, token.Text.Whitespace, "          "),
        (642, token.Text, "Length"),
        (648, token.Text.Whitespace, " "),
        (649, token.Punctuation, ":"),
        (650, token.Text.Whitespace, " "),
        (651, token.Text, "Length"),
        (657, token.Punctuation, ";"),
        (658, token.Text, "\n"),
        (659, token.Text.Whitespace, "          "),
        (669, token.Text, "Data"),
        (673, token.Text.Whitespace, " "),
        (674, token.Punctuation, ":"),
        (675, token.Text.Whitespace, " "),
        (676, token.Text, "Opaque"),
        (682, token.Punctuation, ")"),
        (683, token.Text, "\n"),
        (684, token.Text.Whitespace, "      "),
        (690, token.Keyword, "return"),
        (696, token.Text.Whitespace, " "),
        (697, token.Text, "Definite_Message"),
        (713, token.Punctuation, ";"),
        (714, token.Text, "\n"),
        (715, token.Text.Whitespace, "      "),
        (721, token.Comment, "-- §S-P-F-P-S, §S-P-F-R-S"),
        (746, token.Text, "\n"),
        (747, token.Text.Whitespace, "      "),
        (753, token.Keyword, "with"),
        (757, token.Text.Whitespace, " "),
        (758, token.Keyword, "function"),
        (766, token.Text.Whitespace, " "),
        (767, token.Text, "Valid_Message"),
        (780, token.Text, "\n"),
        (781, token.Text.Whitespace, "         "),
        (790, token.Punctuation, "("),
        (791, token.Text, "Message_Type"),
        (803, token.Text.Whitespace, " "),
        (804, token.Punctuation, ":"),
        (805, token.Text.Whitespace, " "),
        (806, token.Text, "Universal"),
        (815, token.Punctuation, "::"),
        (817, token.Text, "Option_Type"),
        (828, token.Punctuation, ";"),
        (829, token.Text, "\n"),
        (830, token.Text.Whitespace, "          "),
        (840, token.Text, "Strict"),
        (846, token.Text.Whitespace, " "),
        (847, token.Punctuation, ":"),
        (848, token.Text.Whitespace, " "),
        (849, token.Text, "Boolean"),
        (856, token.Punctuation, ")"),
        (857, token.Text, "\n"),
        (858, token.Text.Whitespace, "      "),
        (864, token.Keyword, "return"),
        (870, token.Text.Whitespace, " "),
        (871, token.Text, "Result"),
        (877, token.Punctuation, ";"),
        (878, token.Text, "\n"),
        (879, token.Text.Whitespace, "      "),
        (885, token.Comment, "-- §S-P-F-R-S"),
        (898, token.Text, "\n"),
        (899, token.Text.Whitespace, "      "),
        (905, token.Keyword, "with"),
        (909, token.Text.Whitespace, " "),
        (910, token.Keyword, "function"),
        (918, token.Text.Whitespace, " "),
        (919, token.Text, "Byte_Size"),
        (928, token.Text.Whitespace, " "),
        (929, token.Keyword, "return"),
        (935, token.Text.Whitespace, " "),
        (936, token.Text, "Length"),
        (942, token.Punctuation, ";"),
        (943, token.Text, "\n"),
        (944, token.Text.Whitespace, "   "),
        (947, token.Keyword, "session"),
        (954, token.Text.Whitespace, " "),
        (955, token.Text, "Session"),
        (962, token.Text.Whitespace, " "),
        (963, token.Keyword, "is"),
        (965, token.Text, "\n"),
        (966, token.Text.Whitespace, "      "),
        (972, token.Text, "Message"),
        (979, token.Text.Whitespace, " "),
        (980, token.Punctuation, ":"),
        (981, token.Text.Whitespace, " "),
        (982, token.Text, "Universal"),
        (991, token.Punctuation, "::"),
        (993, token.Text, "Message"),
        (1000, token.Punctuation, ";"),
        (1001, token.Text.Whitespace, " "),
        (1002, token.Comment, "-- §S-D-V-T-M, §S-D-V-E-N"),
        (1027, token.Text, "\n"),
        (1028, token.Text.Whitespace, "      "),
        (1034, token.Text, "Definite_Message"),
        (1050, token.Text.Whitespace, " "),
        (1051, token.Punctuation, ":"),
        (1052, token.Text.Whitespace, " "),
        (1053, token.Text, "Definite_Message"),
        (1069, token.Punctuation, ";"),
        (1070, token.Text.Whitespace, " "),
        (1071, token.Comment, "-- §S-D-V-T-M, §S-D-V-E-N"),
        (1096, token.Text, "\n"),
        (1097, token.Text.Whitespace, "   "),
        (1100, token.Keyword, "begin"),
        (1105, token.Text, "\n"),
        (1106, token.Text.Whitespace, "      "),
        (1112, token.Keyword, "state"),
        (1117, token.Text.Whitespace, " "),
        (1118, token.Text, "Start"),
        (1123, token.Text.Whitespace, " "),
        (1124, token.Keyword, "is"),
        (1126, token.Text, "\n"),
        (1127, token.Text.Whitespace, "      "),
        (1133, token.Keyword, "begin"),
        (1138, token.Text, "\n"),
        (1139, token.Text.Whitespace, "         "),
        (1148, token.Keyword, "Channel"),
        (1155, token.Punctuation, "'"),
        (1156, token.Keyword, "Read"),
        (1160, token.Text.Whitespace, " "),
        (1161, token.Punctuation, "("),
        (1162, token.Text, "Message"),
        (1169, token.Punctuation, ")"),
        (1170, token.Punctuation, ";"),
        (1171, token.Text.Whitespace, " "),
        (1172, token.Comment, "-- §S-S-A-RD-V"),
        (1186, token.Text, "\n"),
        (1187, token.Text.Whitespace, "      "),
        (1193, token.Keyword, "transition"),
        (1203, token.Text, "\n"),
        (1204, token.Text.Whitespace, "         "),
        (1213, token.Keyword, "goto"),
        (1217, token.Text.Whitespace, " "),
        (1218, token.Text, "Process"),
        (1225, token.Text, "\n"),
        (1226, token.Text.Whitespace, "            "),
        (1238, token.Keyword, "if"),
        (1240, token.Text.Whitespace, " "),
        (1241, token.Text, "Message"),
        (1248, token.Punctuation, "'"),
        (1249, token.Keyword, "Valid"),
        (1254, token.Text.Whitespace, " "),
        (1255, token.Comment, "-- §S-S-T-VAT, §S-E-AT-V-V"),
        (1281, token.Text, "\n"),
        (1282, token.Text.Whitespace, "               "),
        (1297, token.Operator.Text, "and"),
        (1300, token.Text.Whitespace, " "),
        (1301, token.Text, "Message"),
        (1308, token.Punctuation, "."),
        (1309, token.Text, "Message_Type"),
        (1321, token.Text.Whitespace, " "),
        (1322, token.Operator, "="),
        (1323, token.Text.Whitespace, " "),
        (1324, token.Text, "Universal"),
        (1333, token.Punctuation, "::"),
        (1335, token.Text, "MT_Data"),
        (1342, token.Text.Whitespace, " "),
        (1343, token.Comment, "-- §S-S-T-S, §S-E-S-V, §S-S-T-L"),
        (1374, token.Text, "\n"),
        (1375, token.Text.Whitespace, "               "),
        (1390, token.Operator.Text, "and"),
        (1393, token.Text.Whitespace, " "),
        (1394, token.Text, "Message"),
        (1401, token.Punctuation, "."),
        (1402, token.Text, "Length"),
        (1408, token.Text.Whitespace, " "),
        (1409, token.Operator, "="),
        (1410, token.Text.Whitespace, " "),
        (1411, token.Literal.Number, "3"),
        (1412, token.Text.Whitespace, " "),
        (1413, token.Comment, "-- §S-S-T-S, §S-E-S-V, §S-S-T-L"),
        (1444, token.Text, "\n"),
        (1445, token.Text.Whitespace, "         "),
        (1454, token.Keyword, "goto"),
        (1458, token.Text.Whitespace, " "),
        (1459, token.Keyword, "null"),
        (1463, token.Text.Whitespace, " "),
        (1464, token.Comment, "-- §S-S-T-N"),
        (1475, token.Text, "\n"),
        (1476, token.Text.Whitespace, "      "),
        (1482, token.Keyword, "exception"),
        (1491, token.Text, "\n"),
        (1492, token.Text.Whitespace, "         "),
        (1501, token.Keyword, "goto"),
        (1505, token.Text.Whitespace, " "),
        (1506, token.Keyword, "null"),
        (1510, token.Text.Whitespace, " "),
        (1511, token.Comment, "-- §S-S-E"),
        (1520, token.Text, "\n"),
        (1521, token.Text.Whitespace, "      "),
        (1527, token.Keyword, "end"),
        (1530, token.Text.Whitespace, " "),
        (1531, token.Text, "Start"),
        (1536, token.Punctuation, ";"),
        (1537, token.Text, "\n\n"),
        (1539, token.Text.Whitespace, "      "),
        (1545, token.Keyword, "state"),
        (1550, token.Text.Whitespace, " "),
        (1551, token.Text, "Process"),
        (1558, token.Text.Whitespace, " "),
        (1559, token.Keyword, "is"),
        (1561, token.Text, "\n"),
        (1562, token.Text.Whitespace, "         "),
        (1571, token.Text, "Valid"),
        (1576, token.Text.Whitespace, " "),
        (1577, token.Punctuation, ":"),
        (1578, token.Text.Whitespace, " "),
        (1579, token.Text, "Result"),
        (1585, token.Punctuation, ";"),
        (1586, token.Text.Whitespace, " "),
        (1587, token.Comment, "-- §S-S-D-V-T-SC"),
        (1603, token.Text, "\n"),
        (1604, token.Text.Whitespace, "         "),
        (1613, token.Text, "Message_Type"),
        (1625, token.Text.Whitespace, " "),
        (1626, token.Punctuation, ":"),
        (1627, token.Text.Whitespace, " "),
        (1628, token.Text, "Universal"),
        (1637, token.Punctuation, "::"),
        (1639, token.Text, "Option_Type"),
        (1650, token.Punctuation, ";"),
        (1651, token.Text.Whitespace, " "),
        (1652, token.Comment, "-- §S-S-D-V-T-SC, §S-S-D-V-E-N"),
        (1682, token.Text, "\n"),
        (1683, token.Text.Whitespace, "         "),
        (1692, token.Text, "Length"),
        (1698, token.Text.Whitespace, " "),
        (1699, token.Punctuation, ":"),
        (1700, token.Text.Whitespace, " "),
        (1701, token.Text, "Length"),
        (1707, token.Punctuation, ";"),
        (1708, token.Text, "\n"),
        (1709, token.Text.Whitespace, "      "),
        (1715, token.Keyword, "begin"),
        (1720, token.Text, "\n"),
        (1721, token.Text.Whitespace, "         "),
        (1730, token.Text, "Message_Type"),
        (1742, token.Text.Whitespace, " "),
        (1743, token.Operator, ":="),
        (1745, token.Text.Whitespace, " "),
        (1746, token.Text, "Get_Message_Type"),
        (1762, token.Punctuation, ";"),
        (1763, token.Text.Whitespace, " "),
        (1764, token.Comment, "-- §S-S-A-A-CL, §S-E-CL-N"),
        (1789, token.Text, "\n"),
        (1790, token.Text.Whitespace, "         "),
        (1799, token.Text, "Valid"),
        (1804, token.Text.Whitespace, " "),
        (1805, token.Operator, ":="),
        (1807, token.Text.Whitespace, " "),
        (1808, token.Text, "Valid_Message"),
        (1821, token.Text.Whitespace, " "),
        (1822, token.Punctuation, "("),
        (1823, token.Text, "Message_Type"),
        (1835, token.Punctuation, ","),
        (1836, token.Text.Whitespace, " "),
        (1837, token.Text, "True"),
        (1841, token.Punctuation, ")"),
        (1842, token.Punctuation, ";"),
        (1843, token.Text.Whitespace, " "),
        (1844, token.Comment, "-- §S-S-A-A-CL, §S-E-CL-L"),
        (1869, token.Text, "\n"),
        (1870, token.Text.Whitespace, "         "),
        (1879, token.Text, "Length"),
        (1885, token.Text.Whitespace, " "),
        (1886, token.Operator, ":="),
        (1888, token.Text.Whitespace, " "),
        (1889, token.Text, "Message"),
        (1896, token.Punctuation, "."),
        (1897, token.Text, "Data"),
        (1901, token.Punctuation, "'"),
        (1902, token.Keyword, "Size"),
        (1906, token.Text.Whitespace, " "),
        (1907, token.Operator, "/"),
        (1908, token.Text.Whitespace, " "),
        (1909, token.Text, "Byte_Size"),
        (1918, token.Punctuation, ";"),
        (1919, token.Text.Whitespace, " "),
        (1920, token.Comment, "-- §S-S-A-A-ME"),
        (1934, token.Text, "\n"),
        (1935, token.Text.Whitespace, "         "),
        (1944, token.Comment, "-- §S-S-A-A-CL, §S-E-CL-V, §S-E-CL-S"),
        (1980, token.Text, "\n"),
        (1981, token.Text.Whitespace, "         "),
        (1990, token.Text, "Definite_Message"),
        (2006, token.Text.Whitespace, " "),
        (2007, token.Operator, ":="),
        (2009, token.Text.Whitespace, " "),
        (2010, token.Text, "Create_Message"),
        (2024, token.Text.Whitespace, " "),
        (2025, token.Punctuation, "("),
        (2026, token.Text, "Message_Type"),
        (2038, token.Punctuation, ","),
        (2039, token.Text.Whitespace, " "),
        (2040, token.Text, "Length"),
        (2046, token.Punctuation, ","),
        (2047, token.Text.Whitespace, " "),
        (2048, token.Text, "Message"),
        (2055, token.Punctuation, "."),
        (2056, token.Text, "Data"),
        (2060, token.Punctuation, ")"),
        (2061, token.Punctuation, ";"),
        (2062, token.Text, "\n"),
        (2063, token.Text.Whitespace, "      "),
        (2069, token.Keyword, "transition"),
        (2079, token.Text, "\n"),
        (2080, token.Text.Whitespace, "         "),
        (2089, token.Keyword, "goto"),
        (2093, token.Text.Whitespace, " "),
        (2094, token.Text, "Reply"),
        (2099, token.Text, "\n"),
        (2100, token.Text.Whitespace, "            "),
        (2112, token.Keyword, "if"),
        (2114, token.Text.Whitespace, " "),
        (2115, token.Text, "Valid"),
        (2120, token.Text.Whitespace, " "),
        (2121, token.Operator, "="),
        (2122, token.Text.Whitespace, " "),
        (2123, token.Text, "M_Valid"),
        (2130, token.Text.Whitespace, " "),
        (2131, token.Comment, "-- §S-S-T-BE"),
        (2143, token.Text, "\n"),
        (2144, token.Text.Whitespace, "         "),
        (2153, token.Keyword, "goto"),
        (2157, token.Text.Whitespace, " "),
        (2158, token.Keyword, "null"),
        (2162, token.Text.Whitespace, " "),
        (2163, token.Comment, "-- §S-S-T-N"),
        (2174, token.Text, "\n"),
        (2175, token.Text.Whitespace, "      "),
        (2181, token.Keyword, "exception"),
        (2190, token.Text, "\n"),
        (2191, token.Text.Whitespace, "         "),
        (2200, token.Keyword, "goto"),
        (2204, token.Text.Whitespace, " "),
        (2205, token.Keyword, "null"),
        (2209, token.Text.Whitespace, " "),
        (2210, token.Comment, "-- §S-S-E"),
        (2219, token.Text, "\n"),
        (2220, token.Text.Whitespace, "      "),
        (2226, token.Keyword, "end"),
        (2229, token.Text.Whitespace, " "),
        (2230, token.Text, "Process"),
        (2237, token.Punctuation, ";"),
        (2238, token.Text, "\n\n"),
        (2240, token.Text.Whitespace, "      "),
        (2246, token.Keyword, "state"),
        (2251, token.Text.Whitespace, " "),
        (2252, token.Text, "Reply"),
        (2257, token.Text.Whitespace, " "),
        (2258, token.Keyword, "is"),
        (2260, token.Text, "\n"),
        (2261, token.Text.Whitespace, "      "),
        (2267, token.Keyword, "begin"),
        (2272, token.Text, "\n"),
        (2273, token.Text.Whitespace, "         "),
        (2282, token.Keyword, "Channel"),
        (2289, token.Punctuation, "'"),
        (2290, token.Keyword, "Write"),
        (2295, token.Text.Whitespace, " "),
        (2296, token.Punctuation, "("),
        (2297, token.Text, "Definite_Message"),
        (2313, token.Punctuation, ")"),
        (2314, token.Punctuation, ";"),
        (2315, token.Text.Whitespace, " "),
        (2316, token.Comment, "-- §S-S-A-WR-V"),
        (2330, token.Text, "\n"),
        (2331, token.Text.Whitespace, "      "),
        (2337, token.Keyword, "transition"),
        (2347, token.Text, "\n"),
        (2348, token.Text.Whitespace, "         "),
        (2357, token.Keyword, "goto"),
        (2361, token.Text.Whitespace, " "),
        (2362, token.Text, "Process_2"),
        (2371, token.Text.Whitespace, " "),
        (2372, token.Comment, "-- §S-S-T-N"),
        (2383, token.Text, "\n"),
        (2384, token.Text.Whitespace, "      "),
        (2390, token.Keyword, "end"),
        (2393, token.Text.Whitespace, " "),
        (2394, token.Text, "Reply"),
        (2399, token.Punctuation, ";"),
        (2400, token.Text, "\n\n"),
        (2402, token.Text.Whitespace, "      "),
        (2408, token.Keyword, "state"),
        (2413, token.Text.Whitespace, " "),
        (2414, token.Text, "Process_2"),
        (2423, token.Text.Whitespace, " "),
        (2424, token.Keyword, "is"),
        (2426, token.Text, "\n"),
        (2427, token.Text.Whitespace, "         "),
        (2436, token.Text, "Length"),
        (2442, token.Text.Whitespace, " "),
        (2443, token.Punctuation, ":"),
        (2444, token.Text.Whitespace, " "),
        (2445, token.Text, "Length"),
        (2451, token.Punctuation, ";"),
        (2452, token.Text, "\n"),
        (2453, token.Text.Whitespace, "      "),
        (2459, token.Keyword, "begin"),
        (2464, token.Text, "\n"),
        (2465, token.Text.Whitespace, "         "),
        (2474, token.Text, "Length"),
        (2480, token.Text.Whitespace, " "),
        (2481, token.Operator, ":="),
        (2483, token.Text.Whitespace, " "),
        (2484, token.Text, "Message"),
        (2491, token.Punctuation, "'"),
        (2492, token.Keyword, "Size"),
        (2496, token.Text.Whitespace, " "),
        (2497, token.Operator, "/"),
        (2498, token.Text.Whitespace, " "),
        (2499, token.Literal.Number, "8"),
        (2500, token.Punctuation, ";"),
        (2501, token.Text.Whitespace, " "),
        (2502, token.Comment, "-- §S-S-A-A-ME"),
        (2516, token.Text, "\n"),
        (2517, token.Text.Whitespace, "         "),
        (2526, token.Comment, "-- §S-S-A-A-CL, §S-E-CL-L, §S-E-CL-V, §S-E-CL-OAT"),
        (2575, token.Text, "\n"),
        (2576, token.Text.Whitespace, "         "),
        (2585, token.Text, "Definite_Message"),
        (2601, token.Text.Whitespace, " "),
        (2602, token.Operator, ":="),
        (2604, token.Text.Whitespace, " "),
        (2605, token.Text, "Create_Message"),
        (2619, token.Text.Whitespace, " "),
        (2620, token.Punctuation, "("),
        (2621, token.Text, "Universal"),
        (2630, token.Punctuation, "::"),
        (2632, token.Text, "OT_Data"),
        (2639, token.Punctuation, ","),
        (2640, token.Text.Whitespace, " "),
        (2641, token.Text, "Length"),
        (2647, token.Punctuation, ","),
        (2648, token.Text.Whitespace, " "),
        (2649, token.Text, "Message"),
        (2656, token.Punctuation, "'"),
        (2657, token.Keyword, "Opaque"),
        (2663, token.Punctuation, ")"),
        (2664, token.Punctuation, ";"),
        (2665, token.Text, "\n"),
        (2666, token.Text.Whitespace, "      "),
        (2672, token.Keyword, "transition"),
        (2682, token.Text, "\n"),
        (2683, token.Text.Whitespace, "         "),
        (2692, token.Keyword, "goto"),
        (2696, token.Text.Whitespace, " "),
        (2697, token.Text, "Reply_2"),
        (2704, token.Text.Whitespace, " "),
        (2705, token.Comment, "-- §S-S-T-N"),
        (2716, token.Text, "\n"),
        (2717, token.Text.Whitespace, "      "),
        (2723, token.Keyword, "exception"),
        (2732, token.Text, "\n"),
        (2733, token.Text.Whitespace, "         "),
        (2742, token.Keyword, "goto"),
        (2746, token.Text.Whitespace, " "),
        (2747, token.Keyword, "null"),
        (2751, token.Text.Whitespace, " "),
        (2752, token.Comment, "-- §S-S-E"),
        (2761, token.Text, "\n"),
        (2762, token.Text.Whitespace, "      "),
        (2768, token.Keyword, "end"),
        (2771, token.Text.Whitespace, " "),
        (2772, token.Text, "Process_2"),
        (2781, token.Punctuation, ";"),
        (2782, token.Text, "\n\n"),
        (2784, token.Text.Whitespace, "      "),
        (2790, token.Keyword, "state"),
        (2795, token.Text.Whitespace, " "),
        (2796, token.Text, "Reply_2"),
        (2803, token.Text.Whitespace, " "),
        (2804, token.Keyword, "is"),
        (2806, token.Text, "\n"),
        (2807, token.Text.Whitespace, "      "),
        (2813, token.Keyword, "begin"),
        (2818, token.Text, "\n"),
        (2819, token.Text.Whitespace, "         "),
        (2828, token.Keyword, "Channel"),
        (2835, token.Punctuation, "'"),
        (2836, token.Keyword, "Write"),
        (2841, token.Text.Whitespace, " "),
        (2842, token.Punctuation, "("),
        (2843, token.Text, "Definite_Message"),
        (2859, token.Punctuation, ")"),
        (2860, token.Punctuation, ";"),
        (2861, token.Text.Whitespace, " "),
        (2862, token.Comment, "-- §S-S-A-WR-V"),
        (2876, token.Text, "\n"),
        (2877, token.Text.Whitespace, "      "),
        (2883, token.Keyword, "transition"),
        (2893, token.Text, "\n"),
        (2894, token.Text.Whitespace, "         "),
        (2903, token.Keyword, "goto"),
        (2907, token.Text.Whitespace, " "),
        (2908, token.Text, "Process_3"),
        (2917, token.Text.Whitespace, " "),
        (2918, token.Comment, "-- §S-S-T-N"),
        (2929, token.Text, "\n"),
        (2930, token.Text.Whitespace, "      "),
        (2936, token.Keyword, "end"),
        (2939, token.Text.Whitespace, " "),
        (2940, token.Text, "Reply_2"),
        (2947, token.Punctuation, ";"),
        (2948, token.Text, "\n\n"),
        (2950, token.Text.Whitespace, "      "),
        (2956, token.Keyword, "state"),
        (2961, token.Text.Whitespace, " "),
        (2962, token.Text, "Process_3"),
        (2971, token.Text.Whitespace, " "),
        (2972, token.Keyword, "is"),
        (2974, token.Text, "\n"),
        (2975, token.Text.Whitespace, "         "),
        (2984, token.Text, "Local_Message"),
        (2997, token.Text.Whitespace, " "),
        (2998, token.Punctuation, ":"),
        (2999, token.Text.Whitespace, " "),
        (3000, token.Text, "Definite_Message"),
        (3016, token.Punctuation, ";"),
        (3017, token.Text, "\n"),
        (3018, token.Text.Whitespace, "      "),
        (3024, token.Keyword, "begin"),
        (3029, token.Text, "\n"),
        (3030, token.Text.Whitespace, "         "),
        (3039, token.Comment, "-- §S-S-A-A-CL, §S-E-CL-L, §S-E-CL-A"),
        (3075, token.Text, "\n"),
        (3076, token.Text.Whitespace, "         "),
        (3085, token.Text, "Local_Message"),
        (3098, token.Text.Whitespace, " "),
        (3099, token.Operator, ":="),
        (3101, token.Text.Whitespace, " "),
        (3102, token.Text, "Create_Message"),
        (3116, token.Text.Whitespace, " "),
        (3117, token.Punctuation, "("),
        (3118, token.Text, "Universal"),
        (3127, token.Punctuation, "::"),
        (3129, token.Text, "OT_Data"),
        (3136, token.Punctuation, ","),
        (3137, token.Text.Whitespace, " "),
        (3138, token.Literal.Number, "2"),
        (3139, token.Punctuation, ","),
        (3140, token.Text.Whitespace, " "),
        (3141, token.Punctuation, "["),
        (3142, token.Literal.Number, "3"),
        (3143, token.Punctuation, ","),
        (3144, token.Text.Whitespace, " "),
        (3145, token.Literal.Number, "4"),
        (3146, token.Punctuation, "]"),
        (3147, token.Punctuation, ")"),
        (3148, token.Punctuation, ";"),
        (3149, token.Text, "\n"),
        (3150, token.Text.Whitespace, "         "),
        (3159, token.Comment, "-- §S-S-A-MFA-S"),
        (3174, token.Text, "\n"),
        (3175, token.Text.Whitespace, "         "),
        (3184, token.Text, "Definite_Message"),
        (3200, token.Punctuation, "."),
        (3201, token.Text, "Length"),
        (3207, token.Text.Whitespace, " "),
        (3208, token.Operator, ":="),
        (3210, token.Text.Whitespace, " "),
        (3211, token.Text, "Local_Message"),
        (3224, token.Punctuation, "."),
        (3225, token.Text, "Length"),
        (3231, token.Punctuation, ";"),
        (3232, token.Text, "\n"),
        (3233, token.Text.Whitespace, "         "),
        (3242, token.Comment, "-- §S-S-A-MFA-S"),
        (3257, token.Text, "\n"),
        (3258, token.Text.Whitespace, "         "),
        (3267, token.Text, "Definite_Message"),
        (3283, token.Punctuation, "."),
        (3284, token.Text, "Data"),
        (3288, token.Text.Whitespace, " "),
        (3289, token.Operator, ":="),
        (3291, token.Text.Whitespace, " "),
        (3292, token.Text, "Local_Message"),
        (3305, token.Punctuation, "."),
        (3306, token.Text, "Data"),
        (3310, token.Punctuation, ";"),
        (3311, token.Text, "\n"),
        (3312, token.Text.Whitespace, "      "),
        (3318, token.Keyword, "transition"),
        (3328, token.Text, "\n"),
        (3329, token.Text.Whitespace, "         "),
        (3338, token.Keyword, "goto"),
        (3342, token.Text.Whitespace, " "),
        (3343, token.Text, "Reply_3"),
        (3350, token.Text.Whitespace, " "),
        (3351, token.Comment, "-- §S-S-T-N"),
        (3362, token.Text, "\n"),
        (3363, token.Text.Whitespace, "      "),
        (3369, token.Keyword, "exception"),
        (3378, token.Text, "\n"),
        (3379, token.Text.Whitespace, "         "),
        (3388, token.Keyword, "goto"),
        (3392, token.Text.Whitespace, " "),
        (3393, token.Keyword, "null"),
        (3397, token.Text.Whitespace, " "),
        (3398, token.Comment, "-- §S-S-E"),
        (3407, token.Text, "\n"),
        (3408, token.Text.Whitespace, "      "),
        (3414, token.Keyword, "end"),
        (3417, token.Text.Whitespace, " "),
        (3418, token.Text, "Process_3"),
        (3427, token.Punctuation, ";"),
        (3428, token.Text, "\n\n"),
        (3430, token.Text.Whitespace, "      "),
        (3436, token.Keyword, "state"),
        (3441, token.Text.Whitespace, " "),
        (3442, token.Text, "Reply_3"),
        (3449, token.Text.Whitespace, " "),
        (3450, token.Keyword, "is"),
        (3452, token.Text, "\n"),
        (3453, token.Text.Whitespace, "      "),
        (3459, token.Keyword, "begin"),
        (3464, token.Text, "\n"),
        (3465, token.Text.Whitespace, "         "),
        (3474, token.Keyword, "Channel"),
        (3481, token.Punctuation, "'"),
        (3482, token.Keyword, "Write"),
        (3487, token.Text.Whitespace, " "),
        (3488, token.Punctuation, "("),
        (3489, token.Text, "Definite_Message"),
        (3505, token.Punctuation, ")"),
        (3506, token.Punctuation, ";"),
        (3507, token.Text.Whitespace, " "),
        (3508, token.Comment, "-- §S-S-A-WR-V"),
        (3522, token.Text, "\n"),
        (3523, token.Text.Whitespace, "      "),
        (3529, token.Keyword, "transition"),
        (3539, token.Text, "\n"),
        (3540, token.Text.Whitespace, "         "),
        (3549, token.Keyword, "goto"),
        (3553, token.Text.Whitespace, " "),
        (3554, token.Keyword, "null"),
        (3558, token.Text.Whitespace, " "),
        (3559, token.Comment, "-- §S-S-T-N"),
        (3570, token.Text, "\n"),
        (3571, token.Text.Whitespace, "      "),
        (3577, token.Keyword, "end"),
        (3580, token.Text.Whitespace, " "),
        (3581, token.Text, "Reply_3"),
        (3588, token.Punctuation, ";"),
        (3589, token.Text, "\n"),
        (3590, token.Text.Whitespace, "   "),
        (3593, token.Keyword, "end"),
        (3596, token.Text.Whitespace, " "),
        (3597, token.Text, "Session"),
        (3604, token.Punctuation, ";"),
        (3605, token.Text, "\n\n"),
        (3607, token.Keyword, "end"),
        (3610, token.Text.Whitespace, " "),
        (3611, token.Text, "Test"),
        (3615, token.Punctuation, ";"),
        (3616, token.Text, "\n"),
    ]


def test_fragment_tokenization() -> None:
    lexer = tools.rflxlexer.RFLXLexer()
    tokens = list(lexer.get_tokens_unprocessed("type T is range 5 .. 127 with Size => 8"))

    assert tokens == [
        (0, token.Keyword, "type"),
        (4, token.Text.Whitespace, " "),
        (5, token.Text, "T"),
        (6, token.Text.Whitespace, " "),
        (7, token.Keyword, "is"),
        (9, token.Text.Whitespace, " "),
        (10, token.Keyword, "range"),
        (15, token.Text.Whitespace, " "),
        (16, token.Literal.Number, "5"),
        (17, token.Text.Whitespace, " "),
        (18, token.Operator, ".."),
        (20, token.Text.Whitespace, " "),
        (21, token.Literal.Number, "127"),
        (24, token.Text.Whitespace, " "),
        (25, token.Keyword, "with"),
        (29, token.Text.Whitespace, " "),
        (30, token.Text, "Size"),
        (34, token.Text.Whitespace, " "),
        (35, token.Operator, "=>"),
        (37, token.Text.Whitespace, " "),
        (38, token.Literal.Number, "8"),
    ]
