name: "Install GNAT Pro"

inputs:
  version:
    required: true
    type: string
  target:
    default: "x86_64"
    required: false
    type: string
  host_arch:
    default: "linux"
    required: false
    type: string
  ssh_key:
    required: true
  server:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        VERSION: ${{ inputs.version }}
        TARGET: ${{ inputs.target }}
        HOST_ARCH: ${{ inputs.host_arch }}
        SSH_KEY: ${{ inputs.ssh_key }}
        SERVER: ${{ inputs.server }}
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_KEY" | tr -d '\r' | ssh-add - &>/dev/null
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan $SERVER >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        scp -q ci@$SERVER:/srv/gnatpro-$VERSION-$TARGET-$HOST_ARCH-bin.tar.gz /home/runner/work/
        tar -C /home/runner/work -xzf /home/runner/work/gnatpro-$VERSION-$TARGET-$HOST_ARCH-bin.tar.gz
        cd /home/runner/work/gnatpro-$VERSION-*$TARGET-$HOST_ARCH-bin && echo -e "\n/home/runner/work/gnat\nY\nY" | ./doinstall
        echo "/home/runner/work/gnat/bin" >> $GITHUB_PATH
