def error(format_str: str, **kwargs: object) -> None: ...
def help(format_str: str, **kwargs: object) -> None: ...  # noqa: A001
def info(format_str: str, **kwargs: object) -> None: ...
def note(format_str: str, **kwargs: object) -> None: ...
def set_quiet(value: bool) -> None: ...
def warning(format_str: str, **kwargs: object) -> None: ...
