class Bounds:
    def __init__(self, lower: int, upper: int) -> None: ...
    def __contains__(self, item: int | Bounds) -> bool: ...
    @property
    def lower(self) -> int: ...
    @property
    def upper(self) -> int: ...
    def merge(self, bounds: Bounds) -> Bounds: ...
