name: commits

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  commit-message-check:
    name: Commit Message Check
    runs-on: ubuntu-20.04
    steps:
      - name: Check FIXUP and WIP
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(?!.*\b(FIXUP|WIP)\b).*'
          flags: 'gi'
          error: 'FIXUP or WIP commits must not be merged into main branch'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
