# This workflow runs all Python-related checks and tests with the latest versions of all development tools.

name: edge tests

on:
  schedule:
    - cron:  '0 2 1 * *'

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [black, isort, flake8, pylint, mypy]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install toolchain
      uses: ada-actions/toolchain@ce2021
      with:
        distrib: community
    - name: Install dependencies
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
        sudo apt install libgmp-dev patchelf
        python -m pip install --upgrade pip wheel
        pip install .[devel]
        pip install --upgrade $(python -c "from importlib.metadata import requires; print(' '.join(r.split(' ')[0] for r in requires('RecordFlux-language') if 'devel' in r))")
    - name: Check
      run: |
        make check_${{ matrix.target }}

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install toolchain
      uses: ada-actions/toolchain@ce2021
      with:
        distrib: community
    - name: Install dependencies
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
        sudo apt install libgmp-dev patchelf
        python -m pip install --upgrade pip wheel
        pip install .[devel]
        pip install --upgrade $(python -c "from importlib.metadata import requires; print(' '.join(r.split(' ')[0] for r in requires('RecordFlux-language') if 'devel' in r))")
    - name: Test
      run: |
        make test
