= User Guide
:toc:
:numbered:

== Specification Files

=== Style Checks

By default, the style of specification files is checked. Style checks can be disabled for individual files by adding a pragma to the first line of the file. Besides the deactivation of specific checks, it is also possible to disable all checks by using `all`.

*Example*

[source,ada,rflx]
----
-- style: disable = line-length, blank-lines

package P is

   ...
----


== Integration Files

For each RecordFlux specification file with the `.rflx` file extension, users
may provide a file with the same name but the `.rfi` file extension. This is
useful to specify buffer sizes for sessions. This file is in the YAML data
format. Buffer sizes are provided in bytes. If no such file is provided,
RecordFlux uses a default buffer size of 4096 bytes.

*Integration file structure*

The following example of an integration file defines, for the session
`My_Session`, a default buffer size of 4096 bytes, a buffer size of 2048 bytes
for the global variable `My_Global_Var`, and a buffer size of 1024 bytes for
the variable `My_State_Variable` defined in the state `My_State`.

[source,yaml]
----
Session:
  My_Session:
    Buffer_Size:
      Default: 4096
      Global:
        My_Global_Var: 2048
      Local:
        My_State:
          My_State_Variable: 1024
----

