variables:
  GNAT_BUILD_DATE: "20220723"
  ANOD_DEFAULT_SANDBOX_DIR: /it/wave

cache:
  paths:
    - node_modules/
 
.setup_gnat: &setup_gnat
    - anod install gnat --build-date $GNAT_BUILD_DATE
    - eval `anod printenv gnat`

.setup_nvm: &setup_nvm
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
    - export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use 

build-client:
  stage: build
  before_script:
    - *setup_nvm
  script:
    - cd client
    - nvm install
    - npm install
    - node --version
    - npm --version
    - npm run compile
  artifacts:
    paths:
      - client/out/*

build-server:
  stage: build
  services:
    - image:recordflux
    - cpu:2
    - mem:4
  before_script:
    - *setup_gnat
  script:
    - python3.8 -m venv .venv
    - source .venv/bin/activate                                                                 
    - make init
    - make install_server_devel
  artifacts:
    paths:
      - .venv/*
      - devutils/*
      - pyproject.toml

test-server:
  stage: test
  services:
    - image:recordflux
    - cpu:2
    - mem:4
  before_script:
    - *setup_gnat
    - source .venv/bin/activate                                                                 
  dependencies:
    - build-server
  script:
    - make check
    - make test_server
