name: tests

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  Checks:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        target: [black, isort, flake8, pylint, mypy]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Determine exact Python version
      run:
        echo "PYTHON_VERSION=$(python -c 'import platform; print(platform.python_version())')" >> $GITHUB_ENV
    - name: Determine current HEAD of RecordFlux
      run:
        echo "RFLX_HEAD=$(git ls-remote https://github.com/Componolit/RecordFlux.git develop | cut -c1-7)" >> $GITHUB_ENV
    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/.local/lib/python${{ matrix.python-version }}/site-packages
          ~/.local/bin
        key: ${{ runner.os }}-python${{ env.PYTHON_VERSION }}-${{ env.RFLX_HEAD }}-${{ hashFiles('requirements.txt') }}
    - name: Install toolchain
      uses: ada-actions/toolchain@ce2020
      with:
        distrib: community
    - name: Install dependencies
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
    - name: Check
      run: |
        make check_${{ matrix.target }}

  Tests:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Determine exact Python version
      run:
        echo "PYTHON_VERSION=$(python -c 'import platform; print(platform.python_version())')" >> $GITHUB_ENV
    - name: Determine current HEAD of RecordFlux
      run:
        echo "RFLX_HEAD=$(git ls-remote https://github.com/Componolit/RecordFlux.git develop | cut -c1-7)" >> $GITHUB_ENV
    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/.local/lib/python${{ matrix.python-version }}/site-packages
          ~/.local/bin
        key: ${{ runner.os }}-python${{ env.PYTHON_VERSION }}-${{ env.RFLX_HEAD }}-${{ hashFiles('requirements.txt') }}
    - name: Install toolchain
      uses: ada-actions/toolchain@ce2020
      with:
        distrib: community
    - name: Install dependencies
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
        echo "PYTEST_ADDOPTS=--basetemp=build" >> $GITHUB_ENV
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
    - name: Test
      run: |
        python3 -m pytest -n $(nproc) -vv
