name: tests

on:
  push:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  Checks:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        target: [black, isort, flake8, pylint, mypy]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Determine exact Python version
      run:
        echo "PYTHON_VERSION=$(python -c 'import platform; print(platform.python_version())')" >> $GITHUB_ENV
    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/.local/lib/python${{ matrix.python-version }}/site-packages
          ~/.local/bin
        key: ${{ runner.os }}-python${{ env.PYTHON_VERSION }}-${{ matrix.target }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install RecordFlux@git+https://github.com/Componolit/RecordFlux.git@develop
        pip install pytest-xdist ${{ matrix.target }}
        echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
    - name: Check
      run: |
        make check_${{ matrix.target }}

  Tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Determine exact Python version
      run:
        echo "PYTHON_VERSION=$(python -c 'import platform; print(platform.python_version())')" >> $GITHUB_ENV
    - name: Determine current HEAD of RecordFlux
      run:
        echo "RFLX_HEAD=$(git ls-remote https://github.com/Componolit/RecordFlux.git develop | cut -c1-7)" >> $GITHUB_ENV
    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/.local/lib/python${{ matrix.python-version }}/site-packages
          ~/.local/bin
        key: ${{ runner.os }}-python${{ env.PYTHON_VERSION }}-${{ env.RFLX_HEAD }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install RecordFlux@git+https://github.com/Componolit/RecordFlux.git@develop
        pip install pytest-xdist
        mkdir $HOME/bin
        echo -e '#!/bin/sh\ndocker run -u $(id -u):$(id -g) -v $HOME:$HOME -w $PWD componolit/ci:gnat-community-2020 gprbuild $@' > $HOME/bin/gprbuild
        chmod +x $HOME/bin/gprbuild
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "$HOME/bin" >> $GITHUB_PATH
        echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
        echo "PYTEST_ADDOPTS=--basetemp=build" >> $GITHUB_ENV
    - name: Test
      run: |
        python3 -m pytest -n $(nproc) -vv
