#!/usr/bin/env python3

"""Generate a GPR file for building the librflxlang.so based on the GPR file generated by langkit."""

from __future__ import annotations

import re
import sys
from pathlib import Path


class GPRGenError(Exception):
    pass


def template(name: str, interfaces: list[str]) -> str:
    interfaces_str = ", ".join([f'"{i}"' for i in interfaces])
    return f"""
with "gnatcoll";

library project Lib{name} is
   for Create_Missing_Dirs use "true";

   for Languages use ("Ada", "C");
   for Source_Dirs use ("src", "langkit/langkit/support", "gnatcoll-bindings/gmp", "gnatcoll-bindings/iconv");
   for Library_Name use "{name}";
   for Library_Kind use "relocatable";
   for Library_Dir use "python/librflxlang";
   for Library_Standalone use "encapsulated";
   for Library_Auto_Init use "True";
   for Interfaces use ({interfaces_str});
   for Object_Dir use "obj/dev";
   package Compiler is
      Common_Args := ("-fPIC", "-g", "-Ofast");
      for Default_Switches ("Ada") use Common_Args & "-gnatn2";
      for Default_Switches ("C") use Common_Args;
   end Compiler;
   for Library_Options use ("-lgmp");
end Lib{name};
"""


def extract(source: str) -> list[str]:
    with open(source, encoding="utf-8") as f:
        data = f.read()
        search = re.search(r"for\s+Interfaces\s+use\s*\(([^)]*)\)\s*;", data)
        if search is None or len(search.groups()) != 1:
            raise GPRGenError(f'Project file "{source}" contains no interfaces')
        return [re.sub(r'^\s*"|"\s*$', "", r) for r in search[1].split(",")]


def generate(libname: str, output_path: Path, input_gpr_file: str) -> None:
    (output_path / f"lib{libname}.gpr").write_text(
        template(libname, extract(input_gpr_file)), encoding="utf-8"
    )


def main() -> None:
    if len(sys.argv) != 4:
        sys.exit(f"Insufficient arguments: {sys.argv[0]} libname output-path input-gpr-file")

    generate(sys.argv[1], Path(sys.argv[2]), sys.argv[3])


if __name__ == "__main__":
    main()
