#!/usr/bin/env python3

"""Write the version generated by setuptools_scm into a json file."""

import json
import sys

from setuptools_scm import get_version

if __name__ == "__main__":
    try:
        VERSION_FILE = sys.argv[1]
    except IndexError:
        VERSION_FILE = "version.json"

    with open(VERSION_FILE, "w", encoding="utf-8") as fd:
        json.dump({"version": get_version()}, fd)
