#!/bin/bash

set -x

docker build -t dhcp-server - <<EOF
FROM alpine:3.12

RUN apk update && apk add dnsmasq && echo "dhcp-range=172.28.1.100,172.28.1.200,1m" > /etc/dnsmasq.conf

CMD dnsmasq -d
EOF

docker network create --subnet=172.28.0.0/16 dhcp-test
docker run --rm --network dhcp-test --cap-add NET_ADMIN --name dhcp-server dhcp-server &
sleep 1
docker run --rm --network dhcp-test --cap-add NET_ADMIN -v $PWD:/app -w /app archlinux:base obj/dhcp_client | tee /dev/tty | grep -q Success
SUCCESS=$?
docker stop dhcp-server
docker network rm dhcp-test

exit $SUCCESS
