#!/bin/bash

set -x
set -o pipefail

ip a a 10.0.0.100/8 dev lo
dnsmasq --no-daemon --dhcp-leasefile=build/dnsmasq.leases --port=1053 --conf-file=$(dirname "$(realpath $0)")/dnsmasq.conf &
DNSMASQ_PID=$!

sleep 2
timeout 5 build/obj/dhcp_client |& sed '/Success/q; $q1'
SUCCESS=$?

kill -9 $DNSMASQ_PID
exit $SUCCESS

trap "kill -9 $DNSMASQ_PID" SIGINT SIGTERM EXIT
