name: "Install SPARK Pro"

inputs:
  version:
    required: true
  ssh_key:
    required: true
  server:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        VERSION: ${{ inputs.version }}
        SSH_KEY: ${{ inputs.ssh_key }}
        SERVER: ${{ inputs.server }}
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_KEY" | tr -d '\r' | ssh-add - &>/dev/null
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan $SERVER >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        scp -q ci@$SERVER:/srv/spark-pro-$VERSION-x86_64-linux-bin.tar.gz /home/runner/work/
        tar -C /home/runner/work -xzf /home/runner/work/spark-pro-$VERSION-x86_64-linux-bin.tar.gz
        cd /home/runner/work/spark-pro-$VERSION-*x86_64-linux-bin && ./doinstall /home/runner/work/spark
        echo "/home/runner/work/spark/bin" >> $GITHUB_PATH
        export PATH=/home/runner/work/spark/bin:$PATH
        gnatprove --version
