name: changelog

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: CHANGELOG.md
          checkNotification: Simple
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
