name: pages

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
   group: "pages"
   cancel-in-progress: true

jobs:
  documentation:
    name: GitHub Pages
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      pages: write
      deployments: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      python-version: "3.8"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Determine exact Python version
        run:
          echo "PYTHON_VERSION=$(python -c 'import platform; print(platform.python_version())')" >> $GITHUB_ENV
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.local/lib/python${{ env.python-version }}/site-packages
            ~/.local/bin
          key: ${{ runner.os }}-python${{ env.PYTHON_VERSION }}-${{ hashFiles('setup.py', 'devutils/setup.cfg') }}
      - name: Cache GNAT Community
        uses: actions/cache@v2
        with:
          path: /home/runner/work/gnat
          key: ${{ runner.os }}-gnat-ce2021
      - name: Install GNAT Community
        uses: ada-actions/toolchain@ce2021
        with:
          distrib: community
          install_dir: /home/runner/work/gnat
      - name: Install dependencies
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
          sudo apt install libgmp-dev patchelf
          python -m pip install --upgrade pip wheel
          make init install_devel
      - name: Generate
        run: |
          make doc
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'doc/build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
