name: publishing

on: push

env:
  ALIRE_VERSION: "1.2.2"
  PYTHON_VERSIONS: |
    3.8
    3.9
    3.10
    3.11

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSIONS }}
      - name: Install Alire
        uses: alire-project/setup-alire@v2
        with:
          version: ${{ env.ALIRE_VERSION }}
          toolchain: "--disable-assistant"
      - name: Install GNAT
        run: |
          make install_gnat
      - name: Build distribution
        run: |
          eval `make printenv_gnat`
          gnat --version
          make pypi_dist
      - name: Store distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-20.04

    environment:
      name: pypi
      url: https://pypi.org/p/RecordFlux

    permissions:
      id-token: write

    steps:
      - name: Download dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-testpypi:
    name: Publish Python distribution to TestPyPI
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    runs-on: ubuntu-20.04

    environment:
      name: testpypi
      url: https://test.pypi.org/p/RecordFlux

    permissions:
      id-token: write

    steps:
      - name: Download dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
